### ISSUE TITLE
Disables standard icons for Settings and Release Notes tabs

### ISSUE THREAD

**Issue by mesosteros** [DanBrooker/file-icons#103]
Whenever the package is enabled it adds icons to the file tree but removes the standard ones from the tab bar, for example, in the case of the Settings and Release Notes tabs.

![file icons](https://cloud.githubusercontent.com/assets/1943233/5629976/605b21be-95b1-11e4-95c1-a44a5b198e1b.gif)

**Comment by DanBrooker** [comment]
Does anyone has any ideas on how to solve this

**Comment by braver** [comment]
I was just discussing this re another package: https://github.com/mark-hahn/web-browser/pull/23#issuecomment-73433864. Not sure you can do it through css though.
