### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by Pixxel** [DanBrooker/file-icons#112]
![icons](https://cloud.githubusercontent.com/assets/1199275/5926955/fb00ff16-a666-11e4-8c58-bca77555b460.png)

Hi - fresh Atom install on 2 machines. No other packages/themes installed. Icons just show an empty square icon.

**Comment by DanBrooker** [comment]
Are there any errors in the developer console?

**Comment by Pixxel** [comment]
All fixed. It was looking for the 'file-icons' folder but the folder in packages was named as 'file-icons-master'. I removed the '-master' bit.
