### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by envygeeks** [DanBrooker/file-icons#118]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `file-icons` package
```
Package.getStylesheetsPath (/opt/atom/share/atom/resources/app/src/package.js:434:9)
Package.getStylesheetPaths (/opt/atom/share/atom/resources/app/src/package.js:445:32)
```

**Comment by DanBrooker** [comment]
What atom version are they changing that? I don't see any issue or deprecation in atom currently.

**Comment by envygeeks** [comment]
It came across today when I updated to v0.181.0

**Comment by DanBrooker** [comment]
Any one else having this issue?

**Comment by zimme** [comment]
I'm getting this warning too.

**Comment by zimme** [comment]
This is wierd. I'm only getting this when i start atom in dev mode.

**Comment by DanBrooker** [comment]
Screenshot would be use, I see this warning on another package.
Changing the stylesheet directory to styles breaks things. Any ideas?

**Comment by envygeeks** [comment]
Maybe @kevinsawicki can provide some insight?

**Comment by kevinsawicki** [comment]
> Changing the stylesheet directory to styles breaks things.

This definitely shouldn't happen (styles and stylesheets should behave exactly the same), can you elaborate on what breaks?

**Comment by DanBrooker** [comment]
@kevinsawicki The real questions is, do I need to change the `stylesheets` to `styles`? 

Renaming to styles is fine (the error was actually something in my personal stylesheet)

**Comment by kevinsawicki** [comment]
> do I need to change the stylesheets to styles?

Yes, you should, for 1.0 API compatibility.

**Comment by DanBrooker** [comment]
Great, thanks for clarifying that

**Comment by DanBrooker** [comment]
Renamed to `styles` in 57d0f65b7d74
