### ISSUE TITLE
New haml icon looks terrible

### ISSUE THREAD

**Issue by finist** [DanBrooker/file-icons#121]
For return old, open Atom > Open your stylesheets, and insert next code:
```
@import "packages/file-icons/styles/colors";
@import "packages/file-icons/styles/icons";
@import "packages/file-icons/styles/items";
@{pane-tab-selector}, .icon-file-text {
  &[data-name$=".haml"]:before   { .html5-icon; .light-red; }
}
```

**Comment by DanBrooker** [comment]
I don't personal use haml but if more people want it reverted to a html5 icon because of "readability" then we should have that discussion

**Comment by finist** [comment]
It will be great!

**Comment by DouweM** [comment]
:+1: for reverting it!

**Comment by Alhadis** [comment]
@finist : How's this look?

<img src="https://cloud.githubusercontent.com/assets/2346707/13290098/82b2b6e0-db66-11e5-897e-1e5d6fbcba99.png" alt="Preview" height="130px" />
