### ISSUE TITLE
Typescript icon would be great.

### ISSUE THREAD

**Issue by binarysqueeze** [DanBrooker/file-icons#132]
A typescript icon would be great, anybody have one ?

**Comment by lazutkin** [comment]
:+1: :+1:

**Comment by lukephills** [comment]
:+1:

**Comment by mrmckeb** [comment]
:+1:

**Comment by mazzy89** [comment]
And please also a typescript react icon (.tsx file)

**Comment by vintem** [comment]
(ok)

**Comment by arodik** [comment]
Yes, need a .tsx icon

**Comment by subjectix** [comment]
I would suggest reusing the .jsx icon. It's pretty enough!
Or maybe a pink shade of it. Since .ts icon is a pink shade of the .js icon.

**Comment by spacejack** [comment]
Would also really like to see this. How about a blue version of the JS icon?

**Comment by sgal** [comment]
How about using the one that is used in [seti-ui](https://github.com/jesseweed/seti-ui) package for atom? I like that package, but I would really like to keep icons separated from the atom theme.

**Comment by JaKXz** [comment]
:+1:

**Comment by ewgenius** [comment]
I added this in my atom stylesheet (color as for .ts files, icon as for .jsx files)
```.less
//...
@import "packages/file-icons/styles/items";
@import "packages/file-icons/styles/colors";
@import "packages/file-icons/styles/icons";
@{pane-tab-selector},
.icon-file-text {
  &[data-name$=".tsx"]:before {
    .react-icon;
    .medium-purple;
  }
}
```
looks like this
![_035](https://cloud.githubusercontent.com/assets/827338/11140277/d222d53a-89e9-11e5-9a66-6d906193c2e6.png)

**Comment by mrpatiwi** [comment]
Added at #232
