### ISSUE TITLE
Broken margins in tabs

### ISSUE THREAD

**Issue by ewgenius** [DanBrooker/file-icons#146]
After last update (1.5.6) some icons in tabs is breaking margins
enabled icons:
![enabled](https://sc-cdn.scaleengine.net/i/cf6e65c95fccc970f289040ba1a69a3e.png)

disabled icons:
![disabled](https://sc-cdn.scaleengine.net/i/966efc94f4630f6aadccb8d598179c08.png)

I'm on elementary linux, atom version - 0.201.0 with default atom-dark theme.

**Comment by Swistaku** [comment]
same on One theme, Mint linux 0.205.0

**Comment by ewgenius** [comment]
with v1.5.7 all is ok
