### ISSUE TITLE
Can I submit you some svg files so you could add it to the package??

### ISSUE THREAD

**Issue by adiultra** [DanBrooker/file-icons#148]
Can I submit you some **svg** files so you could add it to the package??

The Files would be small and would be to the point.

Well C and C++ language icons.

**Comment by DanBrooker** [comment]
Sure, you can also try add them yourself and send a PR

**Comment by Alhadis** [comment]
Support for C and C++ icons was provided in c8da994, so I'd say it's safe to close this. =)
