### ISSUE TITLE
Meteor icon for .meteor folders

### ISSUE THREAD

**Issue by zimme** [DanBrooker/file-icons#150]
Once this FortAwesome/Font-Awesome#4913 is added maybe we can add the meteor icon for .meteor folders.

Also this https://github.com/splendido/MIM2014Slides/blob/master/public/icons/meteor_icon.svg is available.

**Comment by Alhadis** [comment]
@zimme : This was [actioned earlier this year](https://github.com/DanBrooker/file-icons/commit/a6f2d8f7f0ea8d68f5d598a3f58628051d9bb254), so I think this issue's resolved. =)
