### ISSUE TITLE
Cpp/C icons

### ISSUE THREAD

**Issue by nyxus** [DanBrooker/file-icons#156]
Hi, can you add some icons for .cpp / .h / .c / make / cmake files? This will improve C++/C development Atom greatly!

**Comment by DanBrooker** [comment]
I don't make icons so you'll need to find something, have a look at the existing icons fonts used and see if anything would work.

**Comment by Alhadis** [comment]
This now appears to be fixed.

**Comment by ckross01** [comment]
yep fixed in the current version, thanks!
