### ISSUE TITLE
Support variants from existing extensions (.htm and not only .html) 

### ISSUE THREAD

**Issue by 3ffy** [DanBrooker/file-icons#158]
I'm pretty confused about your plugin, it is simple and nice but it supports really few (none?) common extension files variant : 

- it look to be case sensitive (.JPG won't be recognized when .jpg is)

- .htm won't be recognized (when .html is). I assume it's the same about .php and .php5, .php4 etc.

It would be really nice to add (at least) these ones by default !

**Comment by DanBrooker** [comment]
Because this package uses css selectors the rules are case sensitive and exact matches.
It would be very easy to add these variants, PRs welcome

**Comment by Alhadis** [comment]
This was addressed in 6c540c72, so I think it's safe to close this. =)
