### ISSUE TITLE
Composer Icon fix.

### ISSUE THREAD

**Issue by lukasoppermann** [DanBrooker/file-icons#161]
Hey, the composer icon is very hard to see and understand, because of all the fine lines. For Travis the T is used and not the characters, maybe for composer the C could be used instead?

<img width="142" alt="screen shot 2015-07-13 at 10 12 42" src="https://cloud.githubusercontent.com/assets/813754/8645456/db0f061c-2947-11e5-97ca-aafe1a56c641.png">

**Comment by imalitavakoli** [comment]
+1 for fixing the composer icon.

**Comment by Alhadis** [comment]
I'm not sure that's a good solution. Ideally, we shouldn't be making up "improvised" icons like this unless there's seriously no other solution.

Granted, the logo *is* very busy... how would a silhouette look?

<img width="145" alt="screen shot 2016-02-25 at 3 18 54 am" src="https://cloud.githubusercontent.com/assets/2346707/13292092/8ff4947e-db6e-11e5-84a4-bb5c48942640.png">
