### ISSUE TITLE
Icons not shown for all files (although same extension)

### ISSUE THREAD

**Issue by seisfeld** [DanBrooker/file-icons#164]
Hi,

for some reason the icon is not shown for all files, although they have the same extension. Is this an error or am i doing something wrong? I'm quite new to Atom.

cheers
Stephan

<img width="106" alt="example" src="https://cloud.githubusercontent.com/assets/9606362/8772391/28b8a600-2ecc-11e5-9537-52f6f65ebddd.png">

**Comment by DanBrooker** [comment]
That's the expected behaviour. Atom by default assigns the open book icon to README.md because it's a github standard file.

**Comment by seisfeld** [comment]
Thanks for checking!
