### ISSUE TITLE
Please insert icon for gradle and groovy

### ISSUE THREAD

**Issue by phouverneyuff** [DanBrooker/file-icons#166]
I'd like to see a icon with extension .gradle and .groovy.

# Groovy
- url http://www.groovy-lang.org/
- ![image](https://cloud.githubusercontent.com/assets/9394724/8891570/154acc5e-3306-11e5-8f8d-f1837202f82a.png)

# Gradle
- url https://gradle.org/
- Icon 
![image](https://cloud.githubusercontent.com/assets/9394724/8891578/45acc640-3306-11e5-8f44-9dc7b0a1d998.png)

**Comment by abelsromero** [comment]
I vote for this one too.

**Comment by lieko** [comment]
+1 I'd really love to see groovy files icons over there :)

**Comment by andradei** [comment]
:+1:

**Comment by Alhadis** [comment]
I've added both of these in a [pull request](https://github.com/DanBrooker/file-icons/pull/237), but I can't help but laugh at the fact that this issue's been open so long, both languages have since gotten new logos. xD I've used the updates ones instead of those in the OP.
