### ISSUE TITLE
No icons shown since update of theme

### ISSUE THREAD

**Issue by stebiger** [DanBrooker/file-icons#167]
Hi,

I am using atom-material-ui theme by silvestreh - before the update to 0.5.9 the file-icons worked nice and smooth.
Since that update I can not see any icons the tab.

Is this an issue of your package or of theme?

Regards,
Stefan

**Comment by DanBrooker** [comment]
Have you tried the force show icons setting? Some themes hide the icon intentionally

**Comment by stebiger** [comment]
Yes I did - but did not work

**Comment by DanBrooker** [comment]
Ok, I had a look and it's the theme pushing the icons out of view. I tired inspecting the css to see why, but couldn't see any obvious cause/fix.

**Comment by stebiger** [comment]
Ok thank you I think I will open an issue/feature request on the theme.
