### ISSUE TITLE
Please, test icons' colors on a light theme...

### ISSUE THREAD

**Issue by ahmadseleem** [DanBrooker/file-icons#168]
some icons look very bright on a light theme like: One light....
example JS icon

**Comment by roman01la** [comment]
+1 Should turn off color

**Comment by DanBrooker** [comment]
There's a setting to disable colour FYI

**Comment by ahmadseleem** [comment]
I think with colors, is better. but there should be a different set of colors for light UIs....

**Comment by Alhadis** [comment]
[Fixed in v1.7.0](https://github.com/DanBrooker/file-icons/blob/master/CHANGELOG.md#170---2016-04-02).
