### ISSUE TITLE
Git files use gear instead of git icon?

### ISSUE THREAD

**Issue by bsara** [DanBrooker/file-icons#169]
I've noticed that the git files (.gitignore, .gitattributes, etc) all use a gear icon, why not the git icon, would this not make more sense and better set those files apart from others?

**Comment by DanBrooker** [comment]
That's a fair point. 
Currently the .git folder has the git icon and common .git* config files have the cog similar to other config files.
I think it's worth considering.

**Comment by bsara** [comment]
@DanBrooker I'm willing to implement this myself, but I want to make sure that it's what is wanted first.

**Comment by astephenb** [comment]
I would be cool with this.

**Comment by astephenb** [comment]
Closed with #177

**Comment by Alhadis** [comment]
Little late, but I'd just love to thank the OP for recommending this; makes a huge difference. :D Cheers!

**Comment by bsara** [comment]
@Alhadis no problem! I'm loving it too.
