### ISSUE TITLE
PHP Elephant Icon

### ISSUE THREAD

**Issue by anthonyholmes** [DanBrooker/file-icons#180]
What's the possibility of using an elephant icon for PHP like the Seti UI Icons?

**Comment by scherii** [comment]
Oh, I second that. Image for reference:
![](https://raw.githubusercontent.com/jesseweed/seti-ui/master/screenshot.png)

**Comment by Alhadis** [comment]
With all due respect, that'd look kinda ridiculous, even if it *is* the official icon. :\

PHP's icon always has been somewhat... unfortunate.

**Comment by daagar** [comment]
Unfortunate or not, Gradle uses an elephant now for its icon (which has been recently included in file-icons). Good time to go find the old Tim Conway Siamese elephant skit on YouTube.

**Comment by anthonyholmes** [comment]
The icon should just be the php text logo, no shield, if not the elephant.

**Comment by lech** [comment]
Rather than the entire body, just the head would make for an easier-to-identify silhouette. Currently, it's too easy to confuse php/html files at a glance.
