### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by AntouanK** [DanBrooker/file-icons#187]
Thanks for your awesome work.

For `package.json` can we assign an npm logo, or at least a JS icon?

<img width="135" alt="screen shot 2015-09-09 at 12 28 28" src="https://cloud.githubusercontent.com/assets/4569111/9760580/3668e05e-56ee-11e5-9b82-f3a286f5f2b9.png">

**Comment by ckross01** [comment]
Thanks for taking the time to submit an issue.

So I was pondering this one and started looking around at what other editors use for package json files.

The theme I have in sublime text uses this...
<img width="229" alt="screen shot 2015-10-14 at 12 02 57 pm" src="https://cloud.githubusercontent.com/assets/1379666/10489723/215e4944-726c-11e5-8f24-1abe5295e17f.png">

Wasn't sure if you think that would be preferable.

**Comment by AntouanK** [comment]
The curly brackets one can apply in many files I guess. Any JSON, templates, you name it.
The npm logo is clear enough to be specific, and visible in small size.
I'd give it a try with the npm logo.
