### ISSUE TITLE
No icon for gnuplot scripts

### ISSUE THREAD

**Issue by maasha** [DanBrooker/file-icons#191]
Perhaps identified from the hashbang: `#!/usr/bin/env gnuplot`
or `#!/usr/bin/gnuplot`
or extension: `.gp`

**Comment by Alhadis** [comment]
@maasha What exactly would it look like? GNUPlot doesn't even appear to have an icon or logo.

**Comment by maasha** [comment]
How about a coordinate system with a histogram? (much easier than a sinus curve)


![gnuplot](https://cloud.githubusercontent.com/assets/1158057/11456036/c76b36d6-9679-11e5-9c94-a2fd90a722ef.png)

**Comment by Alhadis** [comment]
[Would this do](http://fortawesome.github.io/Font-Awesome/icon/area-chart/)? Bear in mind the axes aren't going to be terribly visible at 16 × 16 resolution, so it could probably do without the arrowheads.

**Comment by maasha** [comment]
Modesty aside I think mine looks more like a plot - not like mountains
through a window frame :o)

And I think we should have a test with and without arrowheads to see the
difference?


Martin

**Comment by Alhadis** [comment]
Hey, I'm an artsy-type. xD Don't be surprised if I can't tell the difference between a plot and a chart/graph/whatever, heh.

But, erm, seriously though, I personally think it's overkill to have a custom icon drawn up for what's essentially something entirely arbitrary. We could use the existing TSV icon (pictured below on the left), which seems kinda suitable. If not, there's the icon I've drawn on the right. I based it around the first image you proposed, but accentuated the details so they stand out better at icon-res:

<img src="https://cloud.githubusercontent.com/assets/2346707/11456227/c8ce240e-96d6-11e5-9e55-a0a332477931.png" width="268" height="147" />

**Comment by maasha** [comment]
I really like the left one!

**Comment by Alhadis** [comment]
Perfect, we're already set, then. =)
