### ISSUE TITLE
Changing file extension does not update currently opened files' tabs

### ISSUE THREAD

**Issue by Petroochio** [DanBrooker/file-icons#193]
When a file is renamed with a different extension the file explorer updates properly, but any open files' tabs do not update the icon unless reopened

**Comment by keyuebao** [comment]
:+1:

**Comment by hgGeorg** [comment]
This seems to be an issue with the [tabs](https://github.com/atom/tabs) package, related to https://github.com/atom/tabs/issues/189. In short: the `data-name` attribute isn't updated correctly after a rename, therefor the css selector sees the old name.

**Comment by n0o0bSina** [comment]
:+1:

**Comment by Alhadis** [comment]
Sorted.
