### ISSUE TITLE
Inconsistent handling of .ico files

### ISSUE THREAD

**Issue by SoullessWaffle** [DanBrooker/file-icons#197]
.ico icons in both the tree view and tabs appear in grey even when the color setting is enabled:
![A](http://puu.sh/kyz9i/ef16c55c16.png)
In addition, .ico files in the tabs don't use the proper image icon:
![B](http://puu.sh/kyyB5/be9bd05277.png)

(I am using the Atom Dark UI Theme + One Dark Syntax Theme on Windows)

**Comment by hgGeorg** [comment]
I think this is vanilla Atom behavior. My PR should fix this.

**Comment by SoullessWaffle** [comment]
:+1:
