### ISSUE TITLE
The Python icon is orange

### ISSUE THREAD

**Issue by arielpontes** [DanBrooker/file-icons#199]
I know the original Python icon is two-color (yellow and blue), which is kind of impossible to reproduce, but at least one of these two colors could be used instead of an entirely different and unrelated one. Or perhaps an intermediary color (some sort of green)? I just installed the package while working on a Python project and I just can't look at an orange icon and think of Python. I added a custom rule to my custom .less file to use an intermediary green tone (`#9ba477`, calculated [here](http://www.w3schools.com/tags/ref_colormixer.asp?colorbottom=F0F8FF&colortop=FFFFFF)), but I thought I should add a issue here because it's a problem I would expect others to also experience.

NOTE: I may be biased towards green because I mostly use Python with Django, but I still think it would better than orange.

**Comment by ckross01** [comment]
I agree the shade of yellow is a bit off from what the python icon looks like. I would be in favor of making the icon a bit more yellow. However, I think that changing it to green is more of the use case for the custom rule so I am not in favor of that.

**Comment by Alhadis** [comment]
Honestly, I think the Python icon should be blue. It's the motif [they use on their own site](https://www.python.org/), and GitHub Linguist [even uses the colour](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2822) to represent the language on this site.

Not really sure where orange came from, now that I think about it.

**Comment by eduardocereto** [comment]
Python is a snake, snakes are green. I think it should be green. Such as this one:

![image](https://cloud.githubusercontent.com/assets/36993/14627459/96b61ce6-05c2-11e6-89cc-6b5c75271bb9.png)

**Comment by Alhadis** [comment]
There's only one way to do this:

<img width="197" alt="screen shot 2016-04-21 at 2 17 20 am" src="https://cloud.githubusercontent.com/assets/2346707/14682074/435da9a0-0767-11e6-9193-33e6ebf55044.png">

We use a cropped version of van Rossum's head as the icon, alleviating all future argument:

<img src="https://cloud.githubusercontent.com/assets/2346707/14682194/cda34552-0767-11e6-97a7-f8b8009124a0.png" width="300" />

**Comment by Alhadis** [comment]
I am way too high for this shit right now.

**Comment by Alhadis** [comment]
Caffeine and sleep-deprivation aside, I think blue is probably a better choice than orange to represent Python. It is, after all, the dominant colour in the site's branding (whereas orange is secondary).

**Comment by krzysztof-sikorski** [comment]
Python icon is featured in `file-icons.png` preview file - I think it should also be updated there.

**Comment by Alhadis** [comment]
Good point. Will fix.
