### ISSUE TITLE
Error compiling Less stylesheet

### ISSUE THREAD

**Issue by labanino** [DanBrooker/file-icons#201]
I'm trying to customize the stylesheet and after adding:
`@import "packages/file-icons/styles/icons";  // to use the defined icons`

I get this error:
`'packages/file-icons/styles/icons.less' wasn't found`

Atom v.1.0.19
OS X El Capitan

**Comment by ckross01** [comment]
thanks for logging an issue.

Is this still happening with latest atom and file-icons? 

I haven't upgraded to EL Capitan yet but will most likely soon and see if I can reproduce this.

**Comment by labanino** [comment]
I read a LOT of complaints about it! So, when this happens don't forget to "install the packages" first, lol. Yes, as simple as that. It works great. Thanks.

**Comment by labanino** [comment]
Closed
