### ISSUE TITLE
SVG Icon Missing

### ISSUE THREAD

**Issue by karbica** [DanBrooker/file-icons#205]
I can't seem to see SVG file icons. Screenshot of what I see in the example directory.

![Screenshot of issue](http://s30.postimg.org/6b37p1hwt/Screen_Shot_2015_10_16_at_11_33_59_AM.png)

**Comment by karbica** [comment]
I converted the icomoon.woff file to .ttf format to view its contents. The icomoon.woff file seems to be missing the SVG icon from Icomoon. I think adding it then regenerating the .woff should work.

**Comment by DanBrooker** [comment]
Is fixed in #202 new version soon
