### ISSUE TITLE
JS icon

### ISSUE THREAD

**Issue by AntouanK** [DanBrooker/file-icons#209]
This line seems to be changing the JS files icon to an ... antenna?
https://github.com/DanBrooker/file-icons/commit/65c2accf7195da6f4ee75a434b4453a07ee78cbc#diff-65aa8dfdba97754cb84150bb589dba59R49

<img width="94" alt="screen shot 2015-10-19 at 12 31 53" src="https://cloud.githubusercontent.com/assets/4569111/10576703/34703d22-765d-11e5-855a-e36b8bed88d4.png">

Made a PR reverting back that icon 
https://github.com/DanBrooker/file-icons/pull/208

**Comment by xlaywan** [comment]
+1

**Comment by jacobmischka** [comment]
Php is also a blackberry icon for some strange reason?
![screenshot from 2015-10-19 08-09-16](https://cloud.githubusercontent.com/assets/3939997/10578598/b66b8ce8-7638-11e5-9965-02cd7cc5baa7.png)

**Comment by ckross01** [comment]
The strange thing for me is that "\f128" didn't work on update for JS, had to restart atom and then it worked. If I change it to "\f148" it now shows a different icon.

Also, if you view the code for the file-icons locally do the icons in the examples folder look correct?

**Comment by hgGeorg** [comment]
Had this issue too... restarting Atom resolved this issue though.

**Comment by jacobmischka** [comment]
Oh, I guess I should have tried that. Thanks.
