### ISSUE TITLE
Updated JS Icon is Bad

### ISSUE THREAD

**Issue by ElegantScripting** [DanBrooker/file-icons#214]
The new icon for JavaScript files is ridiculously ugly. I have no idea what a beacon has to do with JavaScript.

Please change it back to the old one.

**Comment by ckross01** [comment]
Hi, thanks for submitting an issue. After the update for file-icons I restarted Atom and the icon changed to the correct JS file icon.

#209 also reported this issue.

Let me know if this doesn't fix the issue.
