### ISSUE TITLE
Missin SVG icon

### ISSUE THREAD

**Issue by vitto** [DanBrooker/file-icons#217]
It would be nice if SVG icons would be visible in the side bar:

<img width="276" alt="schermata 2015-10-21 alle 12 11 42" src="https://cloud.githubusercontent.com/assets/461484/10633741/0067da44-77ed-11e5-870d-0e7ed73bbc6a.png">

Will them be updated?

Thank you!

**Comment by ckross01** [comment]
Thanks for submitting an issue. I am getting svg icons showing up on the latest version of file icons (1.6.11). If you open the 

Are any other file types not showing in the side bar?

**Comment by vitto** [comment]
I've detected only svg files for now, If i find something more I'll submit the new issues.

Thank you very much, now it works perfect!

<img width="295" alt="schermata 2015-10-31 alle 13 47 33" src="https://cloud.githubusercontent.com/assets/461484/10863666/fa7e660c-7fd5-11e5-8966-d5fc3085b998.png">
