### ISSUE TITLE
Python and Javascript icons are messed up

### ISSUE THREAD

**Issue by arielpontes** [DanBrooker/file-icons#218]
![pyjs](https://cloud.githubusercontent.com/assets/1641431/10637296/8e5fa050-780d-11e5-9640-134ea9a086b0.png)

**Comment by arielpontes** [comment]
Oops, sorry, I closed Atom, re-opened it and now it looks normal again. This bug appeared right after I updated to version 1.6.11 (I'm on a Mac).

**Comment by ckross01** [comment]
Thanks for submitting an issue.

This was also a problem for several others (ref #209), glad restarting solved it for you as well.
