### ISSUE TITLE
Incorrect Icons

### ISSUE THREAD

**Issue by bendacoder** [DanBrooker/file-icons#219]
I just updatedto 1.6.11 and my Python file has the JS icon.

**Comment by ckross01** [comment]
thanks for submitting an issue, we have a few closed issues regarding that problem and a restart of atom fixes it.

Please let me know if this doesn't fix your issue.

**Comment by bendacoder** [comment]
Thank you for your advice. Restarting Atom did fix my problem.

**Comment by DanBrooker** [comment]
I've updated the readme to let people know about this issue.
