### ISSUE TITLE
Add better support for React components

### ISSUE THREAD

**Issue by imalitavakoli** [DanBrooker/file-icons#222]
Hi,

I know that MyComponent.jsx will get the React icon... But if we could have it for MyComponent.react.js file too, that would be great :)

Because that's also a naming convention for having React components according to the Facebook's tutorials and examples, like this one: https://github.com/facebook/flux/tree/master/examples/flux-todomvc/js/components

It was just a thought and suggestion! Thanks a lot for the great work :)

**Comment by ckross01** [comment]
Works for me.
