### ISSUE TITLE
No colours

### ISSUE THREAD

**Issue by ronag** [DanBrooker/file-icons#227]
After the recent update colours stopped working. I've tried uninstalling, restarting atom, reinstalling and finally restarting atom without success. Also tried unchecking and rechecking the "coloured" setting.

**Comment by in-in** [comment]
@ronag your setting looks same?
![set](https://cloud.githubusercontent.com/assets/8797432/11161202/70823566-8a87-11e5-8c85-f08f8ce42cb8.jpg)

**Comment by xHN35RQ** [comment]
I have no colours either. atom 1.2.2, file-icons 1.6.12, settings identical to the above

**Comment by ckross01** [comment]
going to close this issue, if having the colored setting doesnt fix the issue please reopen.


Thanks!
