### ISSUE TITLE
icon for R programming language

### ISSUE THREAD

**Issue by pimentel** [DanBrooker/file-icons#228]
firstly -- thanks for the great package.

I work a lot in [R](https://cran.r-project.org/) and unfortunately there are no icons for it. Any chance he could be added in the next version?

Thanks,

Harold

**Comment by wrathematics** [comment]
Agreed, it would be nice.

R's color is kind of blue based on its (hideous) logo: https://cran.r-project.org/Rlogo.jpg, so anyone in the mean time can add

```
@import "packages/file-icons/styles/colors"; // to use the colours
@import "packages/file-icons/styles/icons";  // to use the defined icons
@import "packages/file-icons/styles/items";
@{pane-tab-selector}, .icon-file-text {
  &[data-name$=".R"]:before,
  &[data-name$=".r"]:before {.medium-blue;}
}
``` 

to your stylesheet (Edit -> Open Your Stylesheet) to color the default icon blue for R fies.  Not perfect, but pretty good.

**Comment by Alhadis** [comment]
That icon came out a hell of a lot better-looking than I expected it to, hahahaha.

**Comment by pimentel** [comment]
Honestly, it looks pretty great. I started using it today. It looks better than the real 1 : -)

**Comment by Alhadis** [comment]
Glad you like it, mate! :-) I had to trace it manually in Adobe Illustrator, because [this](https://cran.r-project.org/Rlogo.jpg) was literally the "best" quality version on Google, hahaha.

**Comment by Alhadis** [comment]
HAHAHAHA, OH MAN, ONLY NOW HAVE I JUST NOTICED THERE'S AN [SVG VERSION OF IT] ON WIKIPEDIA.

Good grief, I'm an idiot. Well, at least it wasn't hard to trace, hahaha.
