### ISSUE TITLE
Title tab content is re-positioned when package is active.

### ISSUE THREAD

**Issue by alice-em** [DanBrooker/file-icons#230]
// 1.6.11 on Fedora23 :: Linux 

When enabled, the content of the title tabs rearranges itself so that the icon is half missing, and the title moves up a few pixels.  I've attached an image to specify.

http://imgur.com/eLzBJEm

**Comment by Alhadis** [comment]
Is this still happening for you? There've been a few updates recently that affected the styling of the file-tab pane.

**Comment by Alhadis** [comment]
@alice-em I'm marking this as closed as I can't reproduce; but if this is still happening in the latest version, please let me know.

**Comment by alice-em** [comment]
Sorry for not being on top of this.

I have a feeling the glitch was caused by the theme I was using and not by file-icons.  I can't tell you which theme it was (I've been through a few), but I think it was a CSS error inside the theme package.

**Comment by Alhadis** [comment]
Quite possibly. There've been a few theme-specific fixes since this was filed, which is why I asked.

And no problem. =)
