### ISSUE TITLE
Update messed up tab icon placement

### ISSUE THREAD

**Issue by DeliciousPickle** [DanBrooker/file-icons#231]
Just installed the latest update, 1.6.11.  It borked the placement of the icons on the tabs.  Icons are now about 1/2 of the icon height lower than they should be, and not aligned with the text.  I'm using the One Dark UI theme and the Monday syntax theme.

**Comment by ckross01** [comment]
does this persist after restarting atom?

**Comment by DeliciousPickle** [comment]
Yes.  I tried re-starting atom and switching to all of the different UI themes.  The error persists for all themes that place the icon on their tabs.  I’m running on Ubuntu 15.10.
Thanks,
Phil

**Comment by Alhadis** [comment]
@DeliciousPickle Is this still happening with the latest release?

**Comment by Alhadis** [comment]
I'm marking this issue as resolved for now: there've been numerous adjustments to alignment and tab-bar icons since this issue was filed.

If this issue persists, please submit another issue (preferably with screenshots). Thank you!
