### ISSUE TITLE
Request for icon: Vue.js *.vue files

### ISSUE THREAD

**Issue by noirbizarre** [DanBrooker/file-icons#234]
Hi! 

I don't how to contribute so will start by simply requesting an icon for `*.vue` files.
They are components for [Vue.js](http://vuejs.org/) loaded by [vue-loader](https://github.com/vuejs/vue-loader) or [vueify](https://github.com/vuejs/vueify).

Syntax highlighting in atom is provided by [vue-language](https://atom.io/packages/language-vue).

**Comment by Alhadis** [comment]
This isn't an easy logo to design a 2-colour variation of... which of these two do you prefer?

![vue](https://cloud.githubusercontent.com/assets/2346707/11454736/9075c264-968c-11e5-89eb-814b19208ad3.png)

Since we can't have intermediate shades for icons, we're reduced to using silhouettes...

**Comment by noirbizarre** [comment]
I like the first one !
