### ISSUE TITLE
Bottom border of inactive tabs hidden / incomplete

### ISSUE THREAD

**Issue by tomow1** [DanBrooker/file-icons#239]
![file-icons-issue-tabs](https://cloud.githubusercontent.com/assets/13496535/11481433/642af58a-9795-11e5-917b-d2fce32a5607.png)
It looks like the background of the tab becomes positioned on top of the bottom border giving the appearance that it is hidden or only partially filled

`vertical-align: middle;` in [styles/items.less](https://github.com/DanBrooker/file-icons/commits/master/styles/items.less) seems to have something to do with it and looking at the history this value has changed back and forth a couple of times.

I managed to work around it by changing this line to `vertical-align: top;` but then the icons don't line up with the tab title text quite as nicely so it's not as simple as changing this alone.
I'm on Windows Atom version 1.2.4
My fork is here d7da4f487c3b902c56a4bea8e4a58260f50e849c

**Comment by tomow1** [comment]
Actually compared to the icons alignment in the tree view, the icons in the tabs do appear a little lower.  Setting `vertical-align: top;` does seem to make them both the same so perhaps this could be considered a fix.
![file-icons-issue-tabs](https://cloud.githubusercontent.com/assets/13496535/11483092/7bba4ddc-979e-11e5-9f7a-faeeb794e5d1.png)

**Comment by ckross01** [comment]
Thanks for the issue and the corresponding pr. I am actually thinking this does look better. I made the changes locally and it does seem to correspond better with the tree view. 

Thanks
