### ISSUE TITLE
Icon for font files

### ISSUE THREAD

**Issue by richarddewit** [DanBrooker/file-icons#241]
A single icon for all font types will suffice :)

* `.ttf`
* `.otf`
* `.woff`
* `.woff2`
* (`.eot` ? )

`.svg` already has an icon

**Comment by ckross01** [comment]
all the currently supported icons have an icon but also a color associated with them.

```
 // Images
  &[data-name$=".JPG"]:before { .image-icon; .medium-green;  }
  &[data-name$=".ICO"]:before { .image-icon; .medium-blue;  }
  &[data-name$=".SVG"]:before { .svg-icon; .dark-yellow;  }
```
Care to take a pass at their color and submit a pr?

**Comment by richarddewit** [comment]
> all the currently supported icons have an icon

Did you mean "currently supported fonts"? Because I only see the default icon for font files.

**Comment by ckross01** [comment]
Yes sorry

**Comment by richarddewit** [comment]
But I'm not seeing any icons for Font files

**Comment by ckross01** [comment]
Sorry, severely lacking coffee this morning. 

If I read your issue correctly you were suggesting that we could repurpose the file-icon we use for svgs, png, etc for font files such as `ttf`. Currently all icons get the same file icon but with different colors associated with them via a style. So we would just have them use the `.svg-icon` or the `.image-icon` and add a color to them such as `.medium-blue`

Which seems fine to me if that is what you were meaning. I would be ok with accepting a pr that includes that.

However if I misunderstood what you were meaning and you had an idea for a different icon for file types that works for me as well.

**Comment by richarddewit** [comment]
That last part is what I meant: an icon for font files.

Something like serif capital Ts:

![](http://files.softicons.com/download/system-icons/crystal-project-icons-by-everaldo-coelho/png/128x128/apps/font.png)

And then apply different colors per font file type
