### ISSUE TITLE
ESLint icons

### ISSUE THREAD

**Issue by IanVS** [DanBrooker/file-icons#243]
Hello, it would be great to use the ESLint icon

<img width="34" alt="screen shot 2015-12-07 at 9 35 29 pm" src="https://cloud.githubusercontent.com/assets/4616705/11646286/843d731c-9d2a-11e5-8dad-afbfeeeea706.png">

 for the following files:

- `.eslintrc`
- `.eslintrc.js`
- `.eslintrc.json`
- `.eslintrc.yml`
- `.eslintrc.yaml`
- `.eslintignore`

I've added it as a custom icon in my own editor and it seems to work well.  I'd be happy to submit a PR if this is agreeable.

**Comment by ckross01** [comment]
Thanks for submitting an issue!

After thinking about it a bit I am inclined to think that some of these should really just display the default for that file extension such as the .yaml file. At least those are my thoughts.

Let's leave the issue open and look for some more feedback.

**Comment by IanVS** [comment]
Okay, sure thing. I guess I have to ask what makes this different from `.bowerrc` or `package.json`, both of which are configuration files which could just as easily have the default icons.  But by giving them their own logos, they are easier to find among more generic files. And, ESLint config files are often spread throughout a project, not just at the root, which in my mind makes them even more necessary to be able to quickly grep visually. 

At any rate, those were my thoughts, and I'll be happy to see what others think. Thanks for making the package hackable, so I could already add it for myself.  :)

**Comment by ckross01** [comment]
Actually that is a very good point with the package.json argument. Some icons in text editors just add {} regardless of what type of json file it is. File-icons, however, does add the npm logo for that one. 

I'd take a pr for this, thanks =)
