### ISSUE TITLE
Openscad files

### ISSUE THREAD

**Issue by skitoo** [DanBrooker/file-icons#244]
Can you add an icon for Openscad files ?

* .scad

Thank you :)

**Comment by Alhadis** [comment]
Ugh, [that logo](https://github.com/openscad/openscad/blob/master/icons/icon.png) will be anything but easy to vectorise into a 2-colour icon. But I'll see what I can do, for the love of 3D. =)

**Comment by skitoo** [comment]
@Alhadis Thank you :)

**Comment by Alhadis** [comment]
How's this look? Recognisable?

<img width="411" alt="screen shot 2016-01-06 at 8 17 24 pm" src="https://cloud.githubusercontent.com/assets/2346707/12139169/8793b856-b4b2-11e5-9b79-69919919bef4.png">

I'm in the middle of preparing a PR, so I can't show you how it'll look scaled down to 16×16 pixels yet... but this is just to give you the general idea.

**Comment by Alhadis** [comment]
Right, something like this:

<img width="184" alt="screen shot 2016-01-06 at 9 40 59 pm" src="https://cloud.githubusercontent.com/assets/2346707/12140718/3650a4ca-b4be-11e5-95e2-b167943343f6.png">

This is a seriously awkward logo to make an icon out of, BTW. It took monumental effort to prevent it looking like a steering wheel, and I'm still not entirely sure I succeeded...

**Comment by skitoo** [comment]
Good for me ! 
Thank you :)
