### ISSUE TITLE
Icons don't show up in tabs with Atom Material

### ISSUE THREAD

**Issue by bradynpoulsen** [DanBrooker/file-icons#253]
I have the `Tab Pane Icon` setting enabled. I use the `Atom Material` theme and syntax. When I open a file with an icon in the file tree, it appears something like:

![screen shot 2015-12-24 at 10 47 06 am](https://cloud.githubusercontent.com/assets/5748275/11996929/e553862e-aa2b-11e5-8a6a-e432cb8b2b41.png)

**Comment by cliffordfajardo** [comment]
I can also confirm, with @bradynpoulsen , that the icons for the tabs don't show up when using the UI Theme Atom Material. 
![setui_atommaterialui](https://cloud.githubusercontent.com/assets/6743796/12383424/b3b2b6ca-bd5a-11e5-8a32-ff837cca45e1.png)

**Comment by MatteoRagni** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4260219/12391586/23777dfe-bde9-11e5-91d9-819e0b5d5d3b.png)

For me icons are shown but there are inconsistency in placing TeX icons and BibTeX icons. The others works fine.

**Comment by ArnaudRinquin** [comment]
The issue actually originate from `Atom Material` default option for `Icon in tabs` being `hidden` ([source](https://github.com/silvestreh/atom-material-ui/blob/42a2d70a67aa760f9c0e6751611400da38315c5a/lib/settings.coffee)). You can restore the icon by changing the option.

From what I see on Atom Material repo, they are going through a major rewrite and this option [is not here anymore](https://github.com/silvestreh/atom-material-ui/blob/master/lib/config-schema.json). I have no idea what's the new default behaviour.

**Comment by Alhadis** [comment]
I've just downloaded and installed the Atom Material theme... everything looks perfectly fine to me.

@bradynpoulsen Is this still an issue?

**Comment by cliffordfajardo** [comment]
This isn't an issue for me anymore
