### ISSUE TITLE
.Rmd Should Leverage the Same Icon as .R

### ISSUE THREAD

**Issue by amormachine** [DanBrooker/file-icons#254]
Fantastic package!

**Issue:**
I notice that [R markdown](http://rmarkdown.rstudio.com/) files (E.g. Those ending in .Rmd) do not share the nice R icon.

**Suggested Fix:**
Both .R and .Rmd files should leverage the R icon already used by the .R files.

**Comment by ckross01** [comment]
Is `.Rmd` files for R mark down ? The file-icons.less already resolves `.rmd` to a mark down icon. Just concerned that trying to resolve the type to multiple icons based on casing could be buggy and a little confusing. 

Let me know, either way I have a pull request that I can quickly change and submit.

Thanks

**Comment by amormachine** [comment]
@ckross01 - Great question.

.Rmd (with the capital R) is the standard file extension for R markdown files generated via RStudio.

Going forward, I see two options given the concern around icons influenced by capitalization:
1. Both .rmd and .Rmd should trigger the markdown icon.
2. Both .rmd and .Rmd should trigger the R icon.

I'm ok with whatever option you think is best, as long as the default text file icon no longer appears for .Rmd :)

Thanks!

**Comment by NilsEnevoldsen** [comment]
There are four types of people we care about:

1. People who use `.R`, `.Rmd`, and `.md`
2. People who use `.R` and `.Rmd`, but not `.md`
3. People who use `.Rmd` and `.md`, but not `.R`
4. People who use `.Rmd`, but not `.md` or `.R`

* It is ambiguous what behavior Type 1 would prefer.
* It is irrelevant what Type 4 would prefer.
* Types 2 and 3 would presumably prefer to see distinct icons for the filetypes they use.
* I would guess that Type 2 outnumbers Type 3.
* Therefore I suggest `.Rmd` (and `.rmd`) have Markdown icons.

**Comment by Alhadis** [comment]
Don't forget: people are still free to customise what icon is displayed if they happen to prefer too many file extensions. :)
