### ISSUE TITLE
Vertical alignment is not consistent across file types

### ISSUE THREAD

**Issue by zyklus** [DanBrooker/file-icons#260]
I have my line-height fairly small in the tree view (20px), so this is more noticeable, I think, than the default layout.  Notice that in the screenshots below, the `.jsx` file's text is bottom-aligned, while the `.html` file is properly middle-aligned.  This roughly is caused by the different font-sizes of the icons.

![image](https://cloud.githubusercontent.com/assets/320562/12375938/c33df78c-bd1c-11e5-89bf-515d528626fc.png)

![image](https://cloud.githubusercontent.com/assets/320562/12375946/fc99caec-bd1c-11e5-8ecf-e9aab3b69d5d.png)

**Comment by Alhadis** [comment]
Bit more to it than that, I'm afraid. There's actually a myriad of different font families, each of which are using noticeably different sizes for each glyph. The manually-set font-sizes are there to try normalising the size discrepancies between the different fonts.

So, short of manually pick through every font we're using and compile them into one neatly-organised superfont (which... I really wouldn't recommend for all the obvious reasons), we're reduced to this constant tennis match batting line-heights and font-sizes around. :-(

**Comment by Alhadis** [comment]
@zyklus This will be resolved in V2, hopefully. Please subscribe to the [relevant task-list](https://github.com/DanBrooker/file-icons/issues/359) for updates.
