### ISSUE TITLE
Maintain a changelog

### ISSUE THREAD

**Issue by andymeneely** [DanBrooker/file-icons#262]
I love this package and I'm really happy to see how active it is. One convention I'm seeing with a lot of Atom packages are keeping a CHANGELOG.md file in the root of the repo. I tend to check that file a lot for most of my packages, and I think this project could use one. Looking at the commit history is too much for me (especially since a lot of them are merges of pull requests in this repo). 

I'm a fan of [keepachangelog.com](http://keepachangelog.com/) conventions and tips for maintaining a changelog.

**Comment by ckross01** [comment]
Definitely a plus one on this, would help just to see what images were added or changed.

**Comment by Alhadis** [comment]
@ckross01: I'll have a crack at tackling this later today. :)

**Comment by ckross01** [comment]
:+1:

**Comment by Alhadis** [comment]
Done! :)

Think we're due for a new release soon? ;-)

**Comment by DanBrooker** [comment]
@Alhadis nicely done!
If you want to push a new release use `apm publish patch` for instance

**Comment by Alhadis** [comment]
Ah, I was leaving that to your discretion. ;-) But I'm happy to do the honours if that's okay. =)

There've been considerable contributions to this package since v1.6.0, should we crank it to v1.7.0 instead of 1.6.15?

**Comment by DanBrooker** [comment]
Considering how much time you've put in, you're most welcome to push.
Not sure about 1.7 vs 1.6.15, not sure it really matters, there haven't been any major changes to how icons are implemented, just more icons and file extensions

**Comment by Alhadis** [comment]
A'ight mate, I think I've done it (I don't use APM for managing versions, so it's a little new to me).

Have settled for v1.6.15. =)
