### ISSUE TITLE
[Request] a raml icon

### ISSUE THREAD

**Issue by jonyeezs** [DanBrooker/file-icons#266]
Hi would be nice to have a raml icon.

Their official logo would be hard to make into an icon though...so not sure how this can be done.
But hey, i'm no designer! :smile:

**Comment by Alhadis** [comment]
[Is this the RAML](http://raml.org/) you're talking about?

If so, that looks incredibly easy... which is why I'm wondering if I've got the wrong "RAML" (which I've never heard of until today).
