### ISSUE TITLE
Possible to put this file-icons into site?

### ISSUE THREAD

**Issue by JuanAntelo** [DanBrooker/file-icons#267]
Hi, 

I'm trying to put these file icons into my website. How can I achieve this? I converted the .less files to css and used the following syntax as a test : 

`<i class="github-icon"></i>`

Did not get any results. How can I achieve this?

**Comment by ckross01** [comment]
Thanks for logging an issue. Without seeing some implementation I am unsure of what the issue might be. Can your CSS even load the images?

If you would like to create a fiddle or something similar someone might be able to help.

**Comment by Alhadis** [comment]
Do you have the icon fonts uploaded?

If so, are you sure the server's sending them with the correct MIME types?

**Comment by juan-orca** [comment]
Thanks for the quick response on this. I will come up with a fiddle to show & will look into using MIME types.

**Comment by JuanAntelo** [comment]
Here's what I came up with : 

http://jsfiddle.net/y4jyh/8/

I basically took a template fiddle that runs LESS and threw all the files in file-icons/styles in there. Then added : 

`.ruby-icon { content: "\f047"; }`
`
<i class="ruby-icon"></i>`

**Comment by Alhadis** [comment]
I'm afraid it doesn't quite work like that, mate. You'll need the [fonts listed here](https://github.com/DanBrooker/file-icons#fonts). The package uses icons from a range of different fonts.

In addition, this repository also uses a custom one for icons that aren't included anywhere else. I've [attached the source files](https://github.com/DanBrooker/file-icons/files/114984/file-icons.zip) for you. :)

**Comment by JuanAntelo** [comment]
Thank you!!
