### ISSUE TITLE
[request] Video file icons

### ISSUE THREAD

**Issue by jaydenseric** [DanBrooker/file-icons#269]
Images have an nice image icon, but videos get the boring fallback.

Can we please add a generic video file icon covering:

- `.webm`
- `.mp4`

And potentially:

- `.ogv`
- `.ogg`

**Comment by Alhadis** [comment]
How's this look, mate? :-)
<img width="198" alt="screen shot 2016-02-02 at 1 10 28 am" src="https://cloud.githubusercontent.com/assets/2346707/12719548/cba2eb2e-c949-11e5-8bbd-7ce7bfaa14aa.png">

**Comment by ckross01** [comment]
:+1:

**Comment by Alhadis** [comment]
Prepping a pull request, along with commits for #266 and #268.

**Comment by jaydenseric** [comment]
The current image icon contains the outline of a file with a bent corner, should the video icon be consistent with that?

Presumably each video format needs a color. There are different colors used for image formats (`.png`, `.jpg`, etc.). How were those colors decided?

**Comment by Alhadis** [comment]
Actually, the video icon is supplied by the Octicons typeface. Which, funnily enough, appears to have changed:
* https://octicons.github.com/icon/file-media/
* https://octicons.github.com/icon/device-camera-video/

Either way, it's probably a lot greppier to see a camera for video and a sheet of paper for 2D images.

As for the colours, well, I'm assuming they were picked at random. I kinda drew the video icon colours based very loosely on the colours of their logos, if any.
