### ISSUE TITLE
File Icons aligned to top when using Remote-Edit

### ISSUE THREAD

**Issue by arda-** [DanBrooker/file-icons#271]
When using the package [remote edit](https://github.com/sveale/remote-edit), the icons seem to be aligned to the top of the tab instead of the window. This occurs with many different file types.

Here are a variety of remotely opened files:
<img width="807" alt="screen shot 2016-02-03 at 11 00 00 am" src="https://cloud.githubusercontent.com/assets/9686548/12793579/27147bea-ca66-11e5-93f3-3f750820d6fb.png">

Here is a remotely opened file next to a local one:
<img width="482" alt="screen shot 2016-02-03 at 11 05 29 am" src="https://cloud.githubusercontent.com/assets/9686548/12793580/2735a9a0-ca66-11e5-95c6-19cebf53a14c.png">

Not quite sure whether this is an issue more appropriate for your project, or the other! [I posted to both, just in case.](https://github.com/sveale/remote-edit/issues/167)

**Comment by Alhadis** [comment]
@arda- Can you pop the inspector tools open and examine the CSS class of the misaligned icon? (View → Developer → Toggle Developer Tools).

I currently don't have access to a remote server where I can reproduce this.

**Comment by sdbarron** [comment]
A local file tab has only a class of "title" while a remote-edit tab has "title icon icon-globe". It seems as if remote-edit is trying to do icon functionality (which sounds good) but it's incompatible with at least this other icon package.

**Comment by Alhadis** [comment]
Right, found it. These lines are the culprit:
<img src="https://cloud.githubusercontent.com/assets/2346707/14048396/144098ea-f302-11e5-977f-c3f29eddc4a6.png" width="291"/>

Patching it right now.

**Comment by Alhadis** [comment]
Alright, done. Sorry about the delay, I was adding a new icon. :) Figure I may as well push both out with the one release.
