### ISSUE TITLE
Color on changes (1.6.14)

### ISSUE THREAD

**Issue by lech** [DanBrooker/file-icons#272]
Unless I'm misunderstanding the option and how it's meant to function, the option to color the file icon on changes doesn't appear to be working as intended.

Currently I have everything except Force Show enabled which gives me a colorless file list and colored tab icons. Unless something is broken, I'm guessing that the tab icons should be colorless as well unless the file has been modified. Or am I interpreting that incorrectly?

**Comment by eduardocereto** [comment]
I believe this only works if you are using git.

**Comment by lech** [comment]
Ahh, got it. I was using it on a few projects without a git repo and noticed that it's working when I was working with a project using git.
