### ISSUE TITLE
Add support for .ko

### ISSUE THREAD

**Issue by demonshreder** [DanBrooker/file-icons#276]

**Comment by Alhadis** [comment]
What's `.ko`? What language?

**Comment by demonshreder** [comment]
.ko is for Linux kernel modules (so C).

**Comment by Alhadis** [comment]
Ah, [they're build objects](http://stackoverflow.com/questions/10476990/difference-between-o-and-ko-file)? Wouldn't it be misleading to label a binary file as a text file? I'm guessing C programmers would be used to recognising C source files with the usual C icon.

**Comment by Alhadis** [comment]
[Perhaps we could use this](https://octicons.github.com/icon/file-binary/)?

**Comment by demonshreder** [comment]
Oh yea that would be confusing.
Yes this icon should do.
Thanks.

**Comment by Alhadis** [comment]
Alright mate, [I've sent a PR](https://github.com/DanBrooker/file-icons/pull/286). =)

**Comment by demonshreder** [comment]
Yay!! Nice. :)
