### ISSUE TITLE
File icon haxe:hxml

### ISSUE THREAD

**Issue by tong** [DanBrooker/file-icons#283]
https://github.com/DanBrooker/file-icons/blob/master/styles/file-icons.less#L528
Haxe build files have the extension `hxml` not `hxsl` (which is haxe-shader-language)

**Comment by Alhadis** [comment]
Should the `hxsl` files retain the Haxe icon, then?

**Comment by tong** [comment]
To be fair to other, more widely used shader languages i would remove it.
Maybe the hxsl authors come up with a custom icon at some point.

**Comment by Alhadis** [comment]
Seems as though this has already been addressed in #282.
