### ISSUE TITLE
Use pattern matching for names

### ISSUE THREAD

**Issue by gfogle** [DanBrooker/file-icons#284]
Apologies if I missed a prior issue about this:

I noticed that it looks like the data-name attribute is what's used to determine the icon to show aka `[ gulpfile.js || gulpfile.coffee || gulpfile.babel.js ]-> .gulp-icon`

I was trying to name some of my files to show the gulp icon in Atom instead of the JS icon by saying `assets.gulpfile.js` instead of `assets.js`... but looks like its very specific selectors in `file-icons.less`... 

thoughts on changing the selectors to `&[data-name*="gulpfile"]:before` which _should_ pick up all files with gulpfile in the name?

**Comment by Alhadis** [comment]
I'm sure it'd work, although there may be false positives. Then again, I'm sure any file with "gulpfile" in its filename somewhere is likely to be Gulp-related.

Should the matching be case-insensitive as well? `&[data-name*="gulpfile" i]:before` (I don't use Gulp or Grunt or any of that tripe, so I've no idea about the possible variations)

**Comment by gfogle** [comment]
> Should the matching be case-insensitive as well? &[data-name*="gulpfile" i]:before (I don't use Gulp or Grunt or any of that tripe, so I've no idea about the possible variations)

Even better! I personally use lowercase style for naming various config files, but I doubt that's a universal naming convention.

**Comment by Alhadis** [comment]
Ugh hell, I might've spoken too soon... the Less compiler throws an error if I try using that flag:

> "LessError: expected ']' got 'i'"

Another reason I hate precompilers... ah well, pattern-matching it is!
