### ISSUE TITLE
Add support for .tag (Riot.js)

### ISSUE THREAD

**Issue by leozdgao** [DanBrooker/file-icons#285]

**Comment by Alhadis** [comment]
Done in #286. Not an easy logo to squash into a 16×16 space, but I tried my best. Here's how it'll look:
<img width="112" alt="screen shot 2016-02-21 at 5 27 18 am" src="https://cloud.githubusercontent.com/assets/2346707/13198392/cddc0e36-d85b-11e5-80cd-fc274e87f377.png">
