### ISSUE TITLE
Failed to load the file-icons package

### ISSUE THREAD

**Issue by elvishp2006** [DanBrooker/file-icons#290]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: elementary OS
**Thrown From**: [file-icons](https://github.com/DanBrooker/file-icons) package, v1.6.15

### Stack Trace

Failed to load the file-icons package

```
At ENOENT: no such file or directory, open '/home/elvis/.atom/packages/file-icons/styles/items.less'

Error: ENOENT: no such file or directory, open '/home/elvis/.atom/packages/file-icons/styles/items.less'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/opt/atom/resources/app.asar/src/theme-manager.js:278:21)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/opt/atom/resources/app.asar/src/theme-manager.js:257:21)
    at /opt/atom/resources/app.asar/src/package.js:433:54
    at Array.map (native)
    at Package.module.exports.Package.loadStylesheets (/opt/atom/resources/app.asar/src/package.js:431:59)
    at /opt/atom/resources/app.asar/src/package.js:112:19
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/opt/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/opt/atom/resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:524:30)
    at /opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /opt/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -2:19.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:15.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:15.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:13.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:08.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -2:06.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:01.8.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -1:37.4.0 core:cut (atom-text-editor.editor.is-focused)
  2x -1:29.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:27.5.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:22.3.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:22.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:22.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:22.2.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:22.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:12.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "projectHome": "/var/www/html"
  },
  "file-icons": {
    "coloured": false
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.7.3
editorconfig, v1.2.4
emmet, v2.4.1
file-icons, v1.6.15
linter, v1.11.3
linter-jshint, v2.0.2
linter-php, v1.1.8
symbol-gen, v1.0.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by kutothe** [comment]
Uninstalling then installing again worked for me.

**Comment by Alhadis** [comment]
@kutothe Hang on, are you saying you were getting that error frequently until you reinstalled?

**Comment by kutothe** [comment]
Unfortunately I didn't copy the exact error, but it said the same thing or else something very similar. It only happened after I updated it earlier today. I'm not sure what version I was on before the update. Uninstalled, then reinstalled, and everything was working. Sorry that I don't have more helpful details about versions and error messages.

**Comment by kutothe** [comment]
I see now on the main README that it suggests to restart Atom before doing anything else. I just wanted to add that I did not restart Atom, but the reinstall worked.

**Comment by Alhadis** [comment]
Yikes, okay, that's weird. :|

What OS are you running, and what packages do you have installed? I assume you're running the latest version of Atom?

**Comment by Alhadis** [comment]
BTW, the part in the readme about restarting Atom was added a long time ago... I doubt it's still relevant anymore. @DanBrooker, do you think it's okay to drop?

**Comment by kutothe** [comment]
I am on the latest version of Atom. OS X 10.11.3.

> apm list --installed --bare


Remote-FTP@0.7.20
atom-autocomplete-php@0.18.7
atom-material-syntax@0.4.3
atom-material-syntax-light@0.4.3
atom-material-ui@1.2.0
color-picker@2.1.1
file-icons@1.6.17
gl-light-syntax@2.2.0
linter@1.11.3
linter-jshint@2.0.2
linter-php@1.2.0
pigments@0.24.2
symbols-tree-view@0.11.0

**Comment by Alhadis** [comment]
Okay, I'm drawing a blank, here. :\ Unfortunately, without knowing the exact error details, I'm unable to determine if it's connected to the reporter's issue. If it happens again, please make sure to open a new issue with full details.

**Comment by TheInsane1990** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [night-syntax](https://github.com/saadq/night-syntax) package 0.2.6


### Stack Trace

Failed to activate the night-syntax theme

```
At error evaluating function `darken`: color.toHSL is not a function in /Users/Turbo/.atom/packages/night-syntax/styles/base.less:154:27

LessError: error evaluating function `darken`: color.toHSL is not a function
  at /packages/night-syntax/styles/base.less:154:27
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.15 
file-icons 2.1.15 
night-syntax 0.2.6 
night-ui 0.1.1 
platformio-ide-terminal 2.7.0 
seti-syntax 1.1.3 
seti-ui 1.9.0 
teletype 0.4.0 
```

**Comment by TheInsane1990** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.15


### Stack Trace

Failed to load the file-icons package

```
At .thicken is undefined in /Users/Turbo/.atom/packages/file-icons/styles/icons.less:29:57

LessError: .thicken is undefined
  at /packages/file-icons/styles/icons.less:29:57
```

### Commands

```
     -1:25 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
```

### Non-Core Packages

```
atom-clock 0.1.15 
file-icons 2.1.15 
night-syntax 0.2.6 
night-ui 0.1.1 
platformio-ide-terminal 2.7.0 
seti-syntax 1.1.3 
seti-ui 1.9.0 
teletype 0.4.0 
```

**Comment by Alhadis** [comment]
@TheInsane1990 Your issue appears entirely unrelated to this package, and the generated report even states that the error originated from the [`night-syntax`](https://github.com/saadq/night-syntax) theme. If this problem persists, please file an issue to the correct repository instead of here. Thank you.
