### ISSUE TITLE
pls add .mp3 logo and color aswell as .ttf and .ttc

### ISSUE THREAD

**Issue by lopy67** [DanBrooker/file-icons#299]
title says it all ^^^^

**Comment by Alhadis** [comment]
We already have an icon for `.ttf` files. I can add a different-coloured variant for TrueType Collections, though (`.ttc).

As for the mp3 logo, well, we can add an icon for all audio formats (the same way we're using an icon for generic vide formats). Octicons doesn't appear to be bundled with one, though, so I suppose we'll need to create one ourselves.
