### ISSUE TITLE
Icon for .babelrc & webpack.config.js?

### ISSUE THREAD

**Issue by kennetpostigo** [DanBrooker/file-icons#304]
Hey,

been using file-icons for sometime. Wondering if maybe you could add file icons for .babelrc files similar to how they were added to .eslintrc . Also wondering if webpack icon could be added to webpack.config.js file.

Thank you 👍🏽

**Comment by Alhadis** [comment]
The Webpack logo is going to be difficult to turn into a 2-colour icon that looks great at 16×16... but I'll try.

Babel's no problem, though. Their logo is even available on their homepage in [SVG format](http://babeljs.io/images/logo.svg).

**Comment by Alhadis** [comment]
@kennetpostigo Does this look okay?

<img width="139" alt="Figure 1" src="https://cloud.githubusercontent.com/assets/2346707/14155184/5bb4afd2-f70c-11e5-9b01-021b5d711092.png">

<img width="223" alt="Figure 2" src="https://cloud.githubusercontent.com/assets/2346707/14155235/988489dc-f70c-11e5-8947-75c19f3abf5c.png">

Communicating transparency through the Gestalt Principle isn't as easy as I thought it'd be, heh.

**Comment by Alhadis** [comment]
Added in e99bc10. Will be included in the next release. =)

**Comment by kennetpostigo** [comment]
Thank you @Alhadis it looks great!
