### ISSUE TITLE
"jade" renamed as "pug"

### ISSUE THREAD

**Issue by nekonenene** [DanBrooker/file-icons#305]
**"jade"** has been renamed as **"pug"**.
( https://github.com/pugjs/pug/issues/2184 )

So, please be available in .pug files like .jade.

file-icons is very helpful package! Thank you always.

**Comment by Alhadis** [comment]
Fixed, mate. :) Will be included in the next release, which'll probably be within the next day or two.

**Comment by nekonenene** [comment]
Thank you very much, I'm so happy!
