### ISSUE TITLE
Support .flowconfig

### ISSUE THREAD

**Issue by AriaFallah** [DanBrooker/file-icons#308]
Currently looks ugly :cry: 

Logo is here: http://flowtype.org/assets/flow-hero-logo.png

![](http://flowtype.org/assets/flow-hero-logo.png)

and the official website: http://flowtype.org/

**Comment by Alhadis** [comment]
[Updated](https://github.com/DanBrooker/file-icons/commit/0313ba7870), mate. =) Will be included in the next release.

**Comment by AriaFallah** [comment]
Thank you! I know it's a just a visual thing, but these file icons make atom so much nicer.

**Comment by Alhadis** [comment]
That's why this package exists, my friend. ;)

**Comment by bjrmatos** [comment]
@Alhadis is possible to add this icon to .flow files? [used for declarations files](https://flowtype.org/docs/declarations.html#declaration-files)

**Comment by Alhadis** [comment]
Of course. =) Are there any other Flow-related files that we should be using this icon for, too?

(I know nothing about Flow)

**Comment by Alhadis** [comment]
Also, is it `.flow`, or `.js.flow`? From the sounds of it, it seems like it should be `.js.flow`.

**Comment by bjrmatos** [comment]
only `.flowconfig` (already done) and `.js.flow`, yes the extension is `.js.flow` 😄

**Comment by Alhadis** [comment]
Done! It's also been a while, so I've cut a new release. =)

**Comment by bjrmatos** [comment]
@Alhadis awesome!!! thnks :heart:
