### ISSUE TITLE
Icon for Broccoli

### ISSUE THREAD

**Issue by leo** [DanBrooker/file-icons#309]
[Broccoli.js](http://broccolijs.com) (basically a asset pipeline) uses files called "Brocfile.js" or "brocfile.js" (case-insensitive) for its builds.

**Comment by Alhadis** [comment]
[On it](https://github.com/broccolijs/broccoli/blob/master/logo/broccoli-logo.svg).

**Comment by leo** [comment]
@Alhadis :metal:

**Comment by Alhadis** [comment]
Should we expect this to work with other JS extensions as well? E.g., `brocfile.es`, `brocfile.jsx`, etc...

**Comment by Alhadis** [comment]
Actually, never mind... I'll assume any filename with `brocfile.` or `Brocfile.` inside it warrants displaying the Broccoli icon. =)

**Comment by leo** [comment]
@Alhadis Yep, that's also my opinion. :blush: Thanks for adding it!
