### ISSUE TITLE
makefile.cson is incorrectly recognized as Makefile

### ISSUE THREAD

**Issue by 50Wliu** [DanBrooker/file-icons#311]
While Makefiles *can* have any file extension, it's somewhat jarring to have all other CSON files have the CSON icon but `makefile.cson` to have the Makefile one :stuck_out_tongue:.

**Comment by Alhadis** [comment]
Is this a common occurrence?

I made `Makefile` a wildcard pattern because of the colossal plethora of various file extensions... I could make an exception for this particular extension, but I'd prefer to know if there are others I should consider too.

**Comment by 50Wliu** [comment]
> Is this a common occurrence?

Nope, pretty sure not.  I'm just working on language-make right now.

**Comment by Alhadis** [comment]
Gotcha.

Actually, I'll remove the wildcard matching for lowercase `makefile`, since it's really `Makefile` that it was added to fix.

**Comment by Alhadis** [comment]
Fixed, mate. =) This'll be included in the next patch release.
