### ISSUE TITLE
Please add .sketch, .ai, .psd

### ISSUE THREAD

**Issue by bennyp123** [DanBrooker/file-icons#312]
Please add common graphic file types.

thanks!

**Comment by Alhadis** [comment]
Sure thing. ;)

**Comment by Alhadis** [comment]
I'm not familiar with `.sketch` files though, what program's used to open them? Google's SketchUp?

**Comment by bennyp123** [comment]
pretty slick vector graphics editor specifically aimed at webmonkeys
http://sketchapp.com/

**Comment by Alhadis** [comment]
Hrm, fair enough. ;)

*continues whooshing around in Illustrator because fuck change*

**Comment by bennyp123** [comment]
here's a screenshot of the doc.icns
<img width="817" alt="screen shot 2016-04-04 at 10 25 43 pm" src="https://cloud.githubusercontent.com/assets/1466420/14260445/377465c6-fab4-11e5-8dd5-6c26f17fb3fc.png">

**Comment by Alhadis** [comment]
Done. ;-) How's it look?

**Comment by bennyp123** [comment]
mighty fine. thanks a mint
<img width="184" alt="screen shot 2016-04-05 at 2 05 48 am" src="https://cloud.githubusercontent.com/assets/1466420/14266730/f92cece2-fad2-11e5-9acf-91a904bf58b3.png">

**Comment by Alhadis** [comment]
Haha, my pleasure! :D
