### ISSUE TITLE
new files not showing icons

### ISSUE THREAD

**Issue by alvaropinot** [DanBrooker/file-icons#316]
For example, a *untitled* tab saved as `something.js` won't show the js icon.

**Comment by alvaropinot** [comment]
maybe related to #193

**Comment by Alhadis** [comment]
Aye, definitely looks like a duplicate (or at least related) issue.

I'll see if there's another way we can fix this...

**Comment by alvaropinot** [comment]
if you need any help, just let me now :)

**Comment by Alhadis** [comment]
Está bien, hombre. ;)

**Comment by Alhadis** [comment]
YA ESTÁ =)
