### ISSUE TITLE
add Phalcon PHP icon files

### ISSUE THREAD

**Issue by jasongutt** [DanBrooker/file-icons#323]
https://phalconphp.com
Two files used in the views are .phtml and .volt

**Comment by Alhadis** [comment]
Hrm, are `.phtml` files the same as the ones being [mentioned here](http://stackoverflow.com/questions/11859015/what-is-phtml-and-when-should-i-use-a-phtml-extension-rather-than-php)?

If not, would it be inaccurate to associate every `.phtml` file with the Phalcon framework?

**Comment by Alhadis** [comment]
I've added it for `.volt` only. Seems like `.phtml` *is* used generically as a PHP-typed markup template.
