### ISSUE TITLE
support nesC lenguage

### ISSUE THREAD

**Issue by carrodher** [DanBrooker/file-icons#324]
**nesC** (network embedded systems C), is a component-based, event-driven programming language used to build applications for the TinyOS platform. **TinyOS** is an operating environment designed to run on embedded devices used in distributed wireless sensor networks. **nesC is built as an extension to the C programming language** with components "wired" together to run applications on TinyOS.

As an extension of C lenguage, the files used in these projects are _.nc_ and _.h_.
The _.h_ files are detected correctly and assigned the icon of the "pink C" but the _ .nc_ files are not assigned any icon.
Can you fix it with a new icon for files _.nc_? Or at least, assign "blue C"  like _.c_ files?

![captura de pantalla de 2016-04-18 17-33-52](https://cloud.githubusercontent.com/assets/13216600/14610016/6d3b0d08-058c-11e6-90bb-eaf10a1e12de.png)

Thank you very much. regards

Some references:
http://www.tinyos.net/
http://tinyos.stanford.edu/tinyos-wiki/index.php/Main_Page

**Comment by Alhadis** [comment]
Sure thing! :)

**Comment by Alhadis** [comment]
YÁ ESTA!

It'll be included in the next patch release. =)

**Comment by carrodher** [comment]
Wow, incredible. Thank you very much! :smiley:
