### ISSUE TITLE
Dust file icon

### ISSUE THREAD

**Issue by lxibarra** [DanBrooker/file-icons#325]
It would be nice if we could have an icon for .dust files. We are using linked inn template engine http://akdubya.github.io/dustjs/ and our files have no icon.

**Comment by Alhadis** [comment]
What icon should these files use?

**Comment by lxibarra** [comment]
Honestly i dont know they dont seem to have anything in the docs or page that can be used as an icon. Linkedinn created it, so maybe for now just the linked inn logo. I will try to contact the dust.js team to see if they can provide some art for it.

**Comment by Alhadis** [comment]
Actually, if it's JavaScript, shouldn't the JS icon just be suitable?

**Comment by lxibarra** [comment]
well at the end its compiled to javascript but the template it self its dust syntax.

```
{#userAuthenticated}
  Welcome!
{/userAuthenticated}
```

**Comment by Alhadis** [comment]
For templating languages, it's generally acceptable to use the target language's icon if there's nothing better (albeit with a different colour).

Using LinkedIn's logo would... probably look really weird.

**Comment by lxibarra** [comment]
Sure i get your point we could use that for now. I open an issue on dust.js repo it self and ask for it maybe they will contribute in the near future.
