### ISSUE TITLE
Support fabfile.py

### ISSUE THREAD

**Issue by eduardocereto** [DanBrooker/file-icons#326]
I use Fabric in all my python projects. It would be awesome to have an icon for it. 

http://www.fabfile.org/

**Comment by eduardocereto** [comment]
Here's the gliph I created with a free online tool I think it came out decent

![image](https://cloud.githubusercontent.com/assets/36993/14622154/f777269c-0595-11e6-94a8-4b78fcb4fb80.png)

**Comment by eduardocereto** [comment]
After some problem getting the woff2 file I think I managed to get it working. 

![image](https://cloud.githubusercontent.com/assets/36993/14627180/fc8271d0-05bf-11e6-9487-ba902ef82c1d.png)

**Comment by Alhadis** [comment]
Yep, looks great!

Just had to remove a few duplicate control points, and change the canvas size so it's square instead of rectangular. I should update `CONTRIBUTING.md` so users are aware of the need to keep SVGs fitted to a square canvas.
