### ISSUE TITLE
Add .graphql file icon

### ISSUE THREAD

**Issue by batjko** [DanBrooker/file-icons#335]
Atom has a package for GraphQL syntax highlighting.
It would be nice to also have a pretty file icon for such files.

The applicable extensions are `.graphql` and perhaps `.gql`, I think?

**Comment by Alhadis** [comment]
Hrm, have you installed the [latest update](https://github.com/DanBrooker/file-icons/releases/tag/v1.7.6#new-icons)?

[I included it in v1.7.6](https://github.com/DanBrooker/file-icons/commit/d93c3cb7294ddf21fe340ffb8e0562355c802aec). =)

**Comment by Alhadis** [comment]
Should I add support for `.gql` too?

**Comment by batjko** [comment]
Well, I am on 1.7.6, but the icon isn't showing up for .graphql:
![image](https://cloud.githubusercontent.com/assets/7287076/14739207/f7fd501a-087d-11e6-93c9-0ce4b87aadb2.png)

![image](https://cloud.githubusercontent.com/assets/7287076/14739205/f4b1c7d8-087d-11e6-8130-631fdeb14111.png)

**Comment by Alhadis** [comment]
Have you restarted Atom?

**Comment by batjko** [comment]
No, because I'm an idiot.
It shows up now :grin: 
![image](https://cloud.githubusercontent.com/assets/7287076/14739546/2486f404-0880-11e6-8712-7cca9deabc23.png)

**Comment by Alhadis** [comment]
Hahaha! No, you're not an idiot, mate... it gets a lot of users, heh. Atom (well, Chromium) only loads fonts once on startup, and doesn't listen for changes. Not that it should waste cycles doing so, either.

I'm wondering if there's a way of telling it to reload typefaces when updating. I'll look into it.

**Comment by batjko** [comment]
I suppose I just assumed it'd refresh seamlessly, because I somehow remember it doing so on previous updates. But I guess it's different when new font items are added, rather than just code changes in the package?

Either way, it looks great. Thanks a lot!

**Comment by Alhadis** [comment]
Ah yeah, it reloads scripts, stylesheets and images, but not fonts (probably because it doesn't expect them to change).

No problem, glad to hear it! :D
