### ISSUE TITLE
Icon is too wide / not scaling properly

### ISSUE THREAD

**Issue by seangates** [DanBrooker/file-icons#345]
![screen shot 2016-04-25 at 10 54 25 am](https://cloud.githubusercontent.com/assets/105656/14791841/d7e7b08c-0ad4-11e6-8a14-350302407ee3.png)

The file icon given isn't scaling properly. This examples uses Marko's icon.

v 1.7.7

**Comment by seangates** [comment]
And ... restarting fixed it.

**Comment by Alhadis** [comment]
Aye, Atom doesn't reload fonts when it's updating packages. That's why I've started to rename the font-file with the appropriate version number, so the program's forced to load the font again. Otherwise, it leaves issues like these lingering with users. =)
