### ISSUE TITLE
Add new icon for .languagebabel files

### ISSUE THREAD

**Issue by cristian-sima** [DanBrooker/file-icons#347]
Hi.

I am using [this package](https://github.com/gandm/language-babel) and it will be very usefull to have the `.languagebabel` icons:

Right now it does not have any icon:
![image](https://cloud.githubusercontent.com/assets/12199042/14849102/cc1e2078-0c79-11e6-8e43-85dc92815aeb.png)

but it will be `very nice` to have the same icon as `.babelrc` files: 

![image](https://cloud.githubusercontent.com/assets/12199042/14849119/dc44d6c2-0c79-11e6-85e2-10421ceb5a0b.png)

**Comment by cristian-sima** [comment]
A big thank you

**Comment by Alhadis** [comment]
An even bigger "you're welcome". ;-)

About to cut a release now.

**Comment by cristian-sima** [comment]
I will check for it
