### ISSUE TITLE
can't show file icon 

### ISSUE THREAD

**Issue by shikelong** [DanBrooker/file-icons#348]
env:
```
   OS: window 10
   atom:1.7.2
```
it look like:

![capture](https://cloud.githubusercontent.com/assets/4499997/14912526/76c5dfc8-0e2f-11e6-97ad-214736e21a20.PNG)

Regards.

**Comment by Alhadis** [comment]
Restarting Atom hasn't helped?

**Comment by Alhadis** [comment]
Restart Atom. Does this still happen?

**Comment by shikelong** [comment]
Restarting Atom hasn't helped.

**Comment by Alhadis** [comment]
Open the inspector tools and select one of the square-shaped icons in the tree view. Then navigate to the bottom-right panel titled "Rendered Fonts". It should look like this:

<img width="264" alt="screen shot 2016-04-29 at 8 16 07 pm" src="https://cloud.githubusercontent.com/assets/2346707/14913563/521bf37a-0e47-11e6-8c17-4afdf78aa4c5.png">

Can you also tell me what other packages you have installed/enabled at the moment?

Has this just happened recently?

**Comment by shikelong** [comment]
### about font render
![capture](https://cloud.githubusercontent.com/assets/4499997/14913668/67a998a6-0e37-11e6-9f8e-b3e877ea894c.PNG)

### the other packages I have installed.
![capture2](https://cloud.githubusercontent.com/assets/4499997/14913673/6cc532fa-0e37-11e6-8294-b99fa057259d.PNG)


 I install the file-icons package by downlown the ZIP package from github. I am a newer to this package,

**Comment by shikelong** [comment]
![capture](https://cloud.githubusercontent.com/assets/4499997/14914021/819328f2-0e39-11e6-9ed0-76223d68fa48.PNG)

**Comment by Alhadis** [comment]
Uh, no no no, that's not how you do it. You need to install packages **through Atom**. You need to remove those folders, close Atom, and restart it. Then do the following steps:

![figure-1](https://cloud.githubusercontent.com/assets/2346707/14914195/76dd1f32-0e4b-11e6-9a90-d52dc4996621.png)

![figure-2](https://cloud.githubusercontent.com/assets/2346707/14914198/7c643846-0e4b-11e6-9bc0-34cf8bd4b31d.png)

![figure-3](https://cloud.githubusercontent.com/assets/2346707/14914203/81e71586-0e4b-11e6-8be0-27c91d523602.png)

**Comment by Alhadis** [comment]
@shikelong I'm closing this for now; if you need any further assistance with installing Atom packages, please consult the [official documentation](http://flight-manual.atom.io/using-atom/sections/atom-packages/). Thank you.

**Comment by shikelong** [comment]
Thank you.
