### ISSUE TITLE
Add icon for *.tsx files

### ISSUE THREAD

**Issue by michael-yx-wu** [DanBrooker/file-icons#349]
Some people use typescript with React and it'd be really nice to have icons for `tsx` files as well. For now, `tsx` files and `jsx` files both use the `jsx` icon.

**Comment by Alhadis** [comment]
Hrm, what icon should `tsx` files use?

I don't use frameworks and refuse to do so, so I'm out of the water with this one. Is there an existing icon we can use, or will `tsx` files require a new one?

**Comment by michael-yx-wu** [comment]
Would it be easy to take the existing jsx icon and turn the j into a t?

**Comment by Alhadis** [comment]
Easy, yes, but eh, it feels like overkill for one extension... wouldn't the React logo be enough?

<img src="https://cloud.githubusercontent.com/assets/2346707/14985375/90b19cfc-118a-11e6-8b23-36a0e6a9f9cb.png" width="300" alt="React" />

It's already included in the package's custom icon-font. =)

**Comment by michael-yx-wu** [comment]
Hm the react logo feels a little weird given the ts and jsx extensions.

**Comment by Alhadis** [comment]
Alright then... I'll add one for `tsx` files. There better not be another fifteen JavaScript frameworks pop up in the next ten minutes, though.

**Comment by michael-yx-wu** [comment]
Thanks!

**Comment by Alhadis** [comment]
You know what's funny? Looking up the name of a language without a logo in Google Images.

<img width="1440" alt="kek" src="https://cloud.githubusercontent.com/assets/2346707/14986084/c590069a-118d-11e6-92c4-7303b6c0da4f.png">

It always ends up with a weird menagerie of unsuspecting developer faces and screenshots. Awesome.

**Comment by michael-yx-wu** [comment]
Well `.tsx` is not really a language per se. It's just using `typescript` with `react`.
