### ISSUE TITLE
v1.7.9 update causes multiple files under git version control to change to the modified color when only one file is edited

### ISSUE THREAD

**Issue by AriaFallah** [DanBrooker/file-icons#352]
Previous discussion here: https://github.com/DanBrooker/file-icons/issues/341

**Comment by Alhadis** [comment]
Alright, could you open your installed version of File-Icons and [make this change](https://github.com/DanBrooker/file-icons/commit/e93cbf53c1771ed235e0cd1c4423c773633b310d)?

I just want to make doubly sure this is the catalyst, because I'm still at a loss as to why I can't replicate it.

**Comment by AriaFallah** [comment]
@Alhadis that did it.

**Comment by AriaFallah** [comment]
It happens if I modify a folder in the `src` directory of this project: https://github.com/AriaFallah/mobx-store

Could you try cloning it and see if you can reproduce there?

**Comment by Alhadis** [comment]
Heh, nope... nothing. :|

At least my hunch about e93cbf5 was right. Will address this by individually targeting every icon that uses the `.medium-yellow` swatch and assigning the darker colour there.

You'll notice we can't simply do `.status-modified .medium-yellow`, because `.medium-yellow` is a Less mixin, and not a class that's actually applied to the file's tree-view entry. :D I LUV PRECOMPILERZ <3 <3 `#noNotReally`

This is another reason I'm looking forward to releasing v2.

**Comment by AriaFallah** [comment]
Ah shucks. Well good luck! I'm not sure why you can't reproduce 😕

**Comment by Alhadis** [comment]
Neither am I. When I'm done, I'll need you to help verify the changes work. So, don't go too far. :p

**Comment by Alhadis** [comment]
Alright... I've pushed what I hope is a fix. Run the following in your shell, please:

```bash
git clone https://github.com/DanBrooker/file-icons.git ~/.atom/dev/packages/file-icons
atom -d your/project/path/here
```

That'll open the folder in Atom using development mode.

**Comment by AriaFallah** [comment]
I also did `rm -rf ~/.atom/packages/file-icons` to be doubly sure that I was using the git cloned one, but it still is not working 😢

Here is a sad short story documenting the issue: https://streamable.com/0laq. As you can see, all the files still change color when I save the changes to just one of them.

**Comment by Alhadis** [comment]
The hell. Does this happen with any other repository, or just this one...?

**Comment by AriaFallah** [comment]
@Alhadis All repos unfortunately. For the time being, I'm fine with using 1.7.8 forever 😅 don't worry about it too much.

**Comment by Alhadis** [comment]
Well, when v2 gets released (hopefully sooner rather than later), you'll definitely want to update. :p And other users might be affected by this, not just you (so I'd prefer this *does* get fixed).

**Comment by Alhadis** [comment]
I'm in the middle of fixing merge conflicts with the v2 branch, so I can't do anything until the stylesheets can compile again.

But honestly, I think the easiest thing to do is simply revert the change after all. All of this trouble's being caused just by adjusting a certain shade of orange to be more noticeable when it's modified.

**Comment by Alhadis** [comment]
@AriaFallah, I've published a patch release. Please let me know if this happens again.

**Comment by AriaFallah** [comment]
Thanks!
