### ISSUE TITLE
Support .sqlite icon

### ISSUE THREAD

**Issue by ptraceur** [DanBrooker/file-icons#353]
Hi,
I have a file called `database.sqlite` I thought the plugin had a specific icon for sqlite files, but it seems not. Could you kindly update with it? (something like .sql would be enought)

This extensions are used for sqlite files:
* .sqlite
* .sqlite3
* .db
* .db3

Thanks for your time, 
have a nice weekend. :)

**Comment by Alhadis** [comment]
Eh? :| I could've sworn this filetype was supported... haha, it's grown so damn big, I can't even keep track anymore. :')

Sure thing!

**Comment by Alhadis** [comment]
Já está! =)

**Comment by ptraceur** [comment]
Obrigado :D
