### ISSUE TITLE
Add Icon for .db (SQL, SQLite, MySQL etc)

### ISSUE THREAD

**Issue by Olian04** [DanBrooker/file-icons#354]

**Comment by Alhadis** [comment]
Hah! Somebody reported the same thing [two hours ago](https://github.com/DanBrooker/file-icons/issues/353). =) I think the universe is trying to tell me something...

... but I feel like a shit person for spamming you folks with so many releases in short succession, haha.

**Comment by Olian04** [comment]
Ohh, sorry about that, should have checked the closed issues before posting.

**Comment by Alhadis** [comment]
Haha, nah it's okay. :D After all, what were the odds?
