### ISSUE TITLE
icon for protractor config

### ISSUE THREAD

**Issue by gdi2290** [DanBrooker/file-icons#362]
it would be great to have a protractor icon
http://www.protractortest.org/#/
![screen shot 2016-05-13 at 1 55 34 pm](https://cloud.githubusercontent.com/assets/1016365/15261598/74aeb6fe-1912-11e6-86b2-462c4e60cfc5.jpg)

**Comment by Alhadis** [comment]
Can do! Are there any other filenames/extensions we should match, or is it just `protractor.conf.js`?

I know nothing about Angular, sorry.

**Comment by gdi2290** [comment]
ya `protractor.conf.js` or `protractor.conf.ts` should be great. thanks!

**Comment by Alhadis** [comment]
Done! ;)
