### ISSUE TITLE
New default file icon

### ISSUE THREAD

**Issue by eboracus** [DanBrooker/file-icons#366]
Currently the default icon that is applied to any file with an unrecognised/unsupported type is a text file icon. I think it would be a lot better if the default was made to be a standard 'blank file/page' icon (as with OS defaults, explorer/finder etc.) and the text icon was used only for text related files. This would help visually distinguish 'known' file types a lot more easily. Maybe to go with version 2 that I see is in the works :)

Something such as `file-empty`, for example, from https://icomoon.io/ seems fairly reasonable, though not mounted an exhaustive search so there maybe something better. [edit: tried in vain to quickly link to image of file 😕]. The icomoon file does seem more rounded than the octicon file icons in shape, not sure if this would aggravating visually or not. Slightly surprised there is no octicon blank file (are they easily modifiable?).

**Comment by Alhadis** [comment]
Not a bad idea, actually. I think the text-file icon is only used as a default because Atom uses it.

> Slightly surprised there is no octicon blank file (are they easily modifiable?)

I'm surprised, myself. They are easily modified, assuming you have the right software... which I do. ;)
