### ISSUE TITLE
Install require `npm cache clean` and do not install

### ISSUE THREAD

**Issue by hemedani** [DanBrooker/file-icons#367]
I'm updating the package after that my pc has a unexpectedly shutdown and then package do not work...
I'm trying to remove and reinstall package but the atom it's not able to find and remove package so I'm running `apm rebuild` and `apm rebuild-module-cache` after that package removing and I can't installed again.
when i want's to install whit this command : `apm install file-icons` it's throw this error :
```
Installing file-icons to /home/abrfa/.atom/packages ✗

npm ERR! tar.unpack error reading /tmp/d-116421-4502-llk3ty/package.tgz
npm ERR! addLocal Could not install /tmp/d-116421-4502-llk3ty/package.tgz
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/abrfa/.atom/.apm/.apmrc" "--userconfig" "/home/abrfa/.atom/.apmrc" "install" "/tmp/d-116421-4502-llk3ty/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116421-4502-19bxn5r/npm-debug.log
```

after cleaning npm cache with `npm cache clean` issues still appear

**Comment by Alhadis** [comment]
NPM? God, this sounds like an issue with `npm` rather than `apm`.

Close Atom, and try this:
```shell
cd ~/.atom/packages
rm -rf file-icons
git clone https://github.com/DanBrooker/file-icons.git
apm link file-icons
```

Does that work?

**Comment by hemedani** [comment]
It's throw this error `Linking /home/abrfa/.atom/packages/file-icons to /home/abrfa/.atom/packages/file-icons failed: EEXIST, file already exists '/home/abrfa/.atom/packages/file-icons'`
but the package working ...

**Comment by Alhadis** [comment]
This actually sounds like an issue with NPM or APM.

Is there anything cached in `~/.atom/.apm/file-icons/`? Atom appears to use that directory to store cached versions, so it might've created the folder and timed out during a transfer. Now there's a partial folder there making it think the version's already installed.

**Comment by hemedani** [comment]
Tanx For your favor

**Comment by hemedani** [comment]
there are this folder :

```
total 40
drwxrwxr-x   6 abrfa abrfa  4096 مه    21 11:21 ./
drwxrwxr-x 470 abrfa abrfa 20480 مه    21 13:04 ../
drwxrwxr-x   3 abrfa abrfa  4096 مه     7 12:36 1.7.10/
drwxrwxr-x   3 abrfa abrfa  4096 مه    12 10:25 1.7.11/
drwxrwxr-x   3 abrfa abrfa  4096 مه    21 11:21 1.7.12/
drwxrwxr-x   3 abrfa abrfa  4096 مه     3 18:59 1.7.8/
```

**Comment by Alhadis** [comment]
Haha, it's no problem, mate. =) Always a pleasure to help.

Alright, wipe those folders out. Just to make sure this is what's caused the issue, please close Atom and run the following:
```shell
cd ~/.atom/packages
apm unlink file-icons
rm -rf file-icons
apm install file-icons
```

Let me know if that works.

**Comment by hemedani** [comment]
It's work greate :

```
Installing file-icons to /home/abrfa/.atom/packages ✓
```

TANX :+1:  :heart:

**Comment by Alhadis** [comment]
Excellent! Glad to hear it. =) Enjoy!
