### ISSUE TITLE
.stylelintrc file loses its icon if I add an extension

### ISSUE THREAD

**Issue by in-in** [DanBrooker/file-icons#369]
.stylelintrc file loses its icon if I add an extension JSON.
Stylelint [configuration guide](http://stylelint.io/user-guide/configuration/) allow this. And I also want to get the syntax highlighting.
![9c061](https://cloud.githubusercontent.com/assets/8797432/15456787/904d776a-2083-11e6-80c7-d8f9661fbac5.png)

atom: 1.7.3
file-icons: 1.7.12

**Comment by Alhadis** [comment]
Done. Note that you can manually specify a file's syntax highlighting in Atom by clicking the language name in the bottom-right corner:
<img src="https://cloud.githubusercontent.com/assets/2346707/15462130/d4b491ba-2103-11e6-8ad1-cac0b1e8fa48.png" width="271" alt="Figure 1" />
This brings the grammar selector which you can use to set the file's language. Note that Atom will remember your choice the next time you open the project, so you needn't repeat this task.

**Comment by in-in** [comment]
I know about this button. But in the new project, it is necessary to click it again. 
Anyway, it's no big deal, I just add the json extension.

**Comment by Alhadis** [comment]
You can also define a customFileType in your user-config file:
```coffee
core:
	customFileTypes:
		"source.json": [
			"stylelintrc"
		]
```
Which will tell Atom to treat all `.stylelintrc` files (in any current or future project) as JSON files.

In either case, the icons will be added in the next release. =)
