### ISSUE TITLE
Icon is applied to folders

### ISSUE THREAD

**Issue by mfuentesg** [DanBrooker/file-icons#373]
This happens when the folder ends with a supported extension.
For example **`jquery.rut.js`**

![screen shot 2016-05-23 at 11 45 28](https://cloud.githubusercontent.com/assets/8986996/15476217/4708a794-20e4-11e6-8a98-821649dca41e.png)

**Comment by Alhadis** [comment]
That's not the JS icon being used by the package. Are you applying a custom icon in your user stylesheet?

If so, you'll need to include `.icon-file-text` in your CSS selector. So it'd be something like this:

```less
.icon-file-text[data-name$=".js"] {
	code-goes: here;
}
```

In either case, I can't reproduce this error on my end: naming a folder `jquery.rut.js` is showing the standard directory icon.

**Comment by mfuentesg** [comment]
i am sorry, I got confused of repository

**Comment by Alhadis** [comment]
Está bien! =)
