### ISSUE TITLE
Different icon for the same extension

### ISSUE THREAD

**Issue by carrodher** [DanBrooker/file-icons#374]
Hello!

I have noticed that files with the same extension (.md markdown) have different icons. The README always has that same book icon and other files markdown have their logo. Is this normal behavior? Why?

![screenshot from 2016-05-25 17-48-35](https://cloud.githubusercontent.com/assets/13216600/15546670/1858c398-22a1-11e6-822f-8efd144ba21a.png)

**Comment by Alhadis** [comment]
Hi Carlos,

Yes, this is normal behaviour. Readme files can have different extensions (`.md`, `.txt`), and they all need to be recognised as readmes.

**Comment by carrodher** [comment]
Perfect! Thanks you!

**Comment by Alhadis** [comment]
Está bien. =)
