### ISSUE TITLE
Feature Request: Add Support for extension-less files with #! lines at their start

### ISSUE THREAD

**Issue by fusion809** [DanBrooker/file-icons#375]
Hi,

I have noticed that this package does not allocate the appropriate icons to files with no file extension but with `#!<PROG>` at their beginning, where `<PROG>` is the location of the command that is intended to execute the file (e.g., `/bin/bash` for Bash scripts, `/bin/sh` for Bourne Shell-compatible scripts, `/usr/bin/python` for Python scripts, etc.). Is this a possibility? 

Thanks for your time,
Brenton

**Comment by Alhadis** [comment]
Support for hashbangs is currently in development and scheduled for v2. =) See the [task list](https://github.com/DanBrooker/file-icons/issues/359) to track progress or make suggestions.
