### ISSUE TITLE
Too much detail in new stylus icon–go with their favicon, instead?

### ISSUE THREAD

**Issue by born2webdesign** [DanBrooker/file-icons#376]
Thanks for the file-icons, love them!
Just the new .styl icon has a bit too much detail for my liking—and compared to other slick icons, messes up the consistent look among the icons a bit, IMO (.svg is a bit heavy, too). How about using stylus' favicon—there is likely a reason, why they chose not to go with the full name for that ;) (just the "s"; preferably on a square(ish) structure, like a document (like .js))

**Comment by Alhadis** [comment]
Hrm, I suppose... although I'm loathe to change the same icon too many times, I find myself agreeing with you (it still kicks the everloving shit out of their [fugly old logo](https://github.com/stylus/stylus/blob/dev/graphics/Vectors/stylus.svg), though).

I find a sphere complements the shape's form than a squarish structure, personally:

<img src="https://cloud.githubusercontent.com/assets/2346707/15672041/78793936-2771-11e6-9e7b-acbac7403c10.png" width="164" alt="Figure 1" />

Although the unadorned form doesn't do too badly, either:
<img src="https://cloud.githubusercontent.com/assets/2346707/15672061/97630f8e-2771-11e6-9de8-6c4850188a3d.png" width="164" alt="Figure 2" />

I don't understand the CSS precompiler-world's obsession with [logos which make shit icons](https://github.com/DanBrooker/file-icons/pull/371#issuecomment-220987151), it just doesn't make sense.

**Comment by born2webdesign** [comment]
:D Yea, I guess, the round one looks "stylish" enough ;)
(of course, it was ambiguous, but stylistically, I still liked the old "css3" icon for .styl)

**Comment by Alhadis** [comment]
Well, you're free to override the icon in your stylesheet. =)

Anyway, I'll add both variants, but set Stylus to use the unenclosed variant. People who prefer the orb or the current Stylus icon can always set them in their stylesheets.

**Comment by Alhadis** [comment]
@born2webdesign Done in 1980feb!

That's not a date, that's the SHA hash of the freaking commit, hahahahaha. What a combo.
