### ISSUE TITLE
Suggestion: Have a custom icon for the node_modules folder

### ISSUE THREAD

**Issue by sbrl** [DanBrooker/file-icons#378]
The `.git` folder already has its own icon. I suggest that the `mode_modules`  folder has one too.

**Comment by Alhadis** [comment]
Probably a good idea, actually. Would the [hexagon-shaped "JS" part of the Node logo](https://nodejs.org/static/images/logos/nodejs-new-white-pantone.png) be enough?

**Comment by sbrl** [comment]
Yeah, that looks good!

**Comment by Alhadis** [comment]
Done.

**Comment by sbrl** [comment]
Thanks!

**Comment by Everesty** [comment]
Funny, I thought of this a few months back but for some reason never acted on it. I just revisited the idea only to find it very recently resolved.
