### ISSUE TITLE
IcoMoon not giving me a woff2 to copy?

### ISSUE THREAD

**Issue by jacobmischka** [DanBrooker/file-icons#379]
I tried following the directions in CONTRIBUTING.md, but IcoMoon doesn't seem to be giving me a woff2 file, just .eot, .svg, .ttf, and .woff. Am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/3939997/15826710/3aebc744-2bce-11e6-9b57-ecddd7808356.png)

**Comment by Alhadis** [comment]
Eh?? That's seriously odd, and it shouldn't have happened. :|

Uhm, I can't reproduce, and can't think of anything that would've caused this. Did you change any of the preferences in IcoMoon settings? (That shouldn't have affected anything, but I'm just trying to cover all ground, here).

**Comment by jacobmischka** [comment]
Arch Linux, but I don't know why it would matter. Not to my knowledge, but I'll try the whole process again and see if I imported selection.json incorrectly.

**Comment by Alhadis** [comment]
No it shouldn't matter, you're right. Not sure why I asked now (my knee-jerk reaction to seeing weird shit is to ask questions).

**Comment by jacobmischka** [comment]
Yeah, I don't know what I'm doing wrong, here's my selection.json, could you try importing it into IcoMoon and see if you can see anything wrong? https://gist.github.com/jacobmischka/fedf0753de7c9545c76242a44621ffc8

Thanks!

**Comment by Alhadis** [comment]
Wait, I know what it is. I completely forgot that IcoMoon [only permits premium users](https://icomoon.io/#premium) to generate WOFF2 fonts... :\ Could you Gist the SVG for me?

Think I'm gonna have to rethink our procedure for updating the font...

**Comment by jacobmischka** [comment]
Oh lol, sure: https://gist.github.com/jacobmischka/7e0be5e99a4edce56554bfe3098d384d

It's the icon for [Rollup](http://rollupjs.org/).

Thanks!

**Comment by Alhadis** [comment]
Thanks! Sorry about the inconvenience/confusion. :( Had I remembered WOFF2 fonts were premium-only, I definitely would've worded the contributor notes better.

I'll add it now.

**Comment by jacobmischka** [comment]
No problem, also I forgot to mention the default filename is rollup.config.js, much like webpack's webpack.config.js.

**Comment by Alhadis** [comment]
Got it. =)

BTW, I'm just gonna take a moment to clean the file's geometry up in Illustrator. There're a lot of control points that can be left out, and I'm trying to keep the font's size as optimum as possible.

(Yes, I'm an meticulous, obsessive shithead. :') I make no apologies for knowing who I am, hahaha)

**Comment by jacobmischka** [comment]
Sure that's fine, I just copied it from the site and changed the strokes to paths and changed the color, I take no pride in the icon :smile:

**Comment by Alhadis** [comment]
Nah you're right, mate. It's actually pretty common for font authors not to care about how geometry-heavy their icons are. I actually squashed 17 KBs out of a [WOFF2 font](https://github.com/Alhadis/DevOpicons) simply by cleaning up geometry...
