### ISSUE TITLE
Vagrantfile icon looks crunchy

### ISSUE THREAD

**Issue by monkpit** [DanBrooker/file-icons#381]
First of all, thanks for making this package! I really love having these extra icons - it makes identifying items my project tree take literally no time at all.

Lately I've been working on a project that involves having a Vagrantfile in the root directory (so I'm always looking at it ;) )

I've opened up the font file itself and I can see how the Vagrantfile icon matches the vibe of the Vagrant logo created by Hashicorp. However, when the icons are shown at a smaller scale (font size 10-16 on a 27" Thunderbolt screen at 2560x1440) the icon kinda looks like it got chewed on a little bit.

![screen shot 2016-06-10 at 8 40 35 am](https://cloud.githubusercontent.com/assets/5297293/15966074/09fccd74-2ee7-11e6-8f84-b8bc71b36502.png)

I'm not sure if there's a way you could handle this. Maybe changing the icon at lower font sizes to just be a plain stylized V character.

Anyways, thanks again for making this package and updating it so regularly! Cheers.

**Comment by Alhadis** [comment]
I'm afraid there's not much that can be done about the Vagrantfile character... it was a difficult logo to create an icon out of (and it looked much worse when I tried leaving the holes in...). I suppose I could add a variant where the edges aren't chewed... would that help?

(Some logos are just a plain pain-in-the-arse to work with...)

Also, thanks for the kind words! =)

**Comment by monkpit** [comment]
That's kinda what I was thinking as well, just create a version that looks like a solid V without any munchy parts. Thanks again :)

**Comment by Alhadis** [comment]
Actually, screw it, the icon looks better without the erosion anyway. It's hardly recognisable at such a small size, so, you're right, it's better this way. =)

Done.

**Comment by monkpit** [comment]
@Alhadis you rock - just FYI.

**Comment by Alhadis** [comment]
<3 Nawh, thanks mate.
