### ISSUE TITLE
TypeDoc icon?

### ISSUE THREAD

**Issue by gdi2290** [DanBrooker/file-icons#383]
http://typedoc.io/
<img width="196" alt="screen shot 2016-06-11 at 2 46 31 pm" src="https://cloud.githubusercontent.com/assets/1016365/15987626/4f6bf180-2fe3-11e6-9024-97207a079aed.png">
do you think we can have a typedoc icon?

**Comment by Alhadis** [comment]
Would either of these work?

<img src="https://cloud.githubusercontent.com/assets/2346707/15989981/070eb7ea-30cb-11e6-9653-73b783d9b2f0.png" width="24" alt="Icon 1" /> <img src="https://cloud.githubusercontent.com/assets/2346707/15989984/131139dc-30cb-11e6-899e-a4719beb3593.png" width="24" alt="Icon 2" />

Personally I prefer the second one.

**Comment by gdi2290** [comment]
I like the second one, thanks!

**Comment by Alhadis** [comment]
Done, and done!
