### ISSUE TITLE
File icons not displayed

### ISSUE THREAD

**Issue by raphaelokon** [DanBrooker/file-icons#385]
Is this issue related to icons not being displayed (I can only see a rectangle instead of the icon).
I have my atom config folder at ~/somepath/.atom fyi

And yes – I restarted my atom :-)

Atom v1.8
Latest file-icons

**Comment by Alhadis** [comment]
Is there anything in your user stylesheet that might be targeting file-icons?

Also, what other packages and themes do you have installed? Run `apm list -ib` at the terminal and show us the output.

It would also help if we had a screenshot, just so we can see what you're talking about.

**Comment by raphaelokon** [comment]
> Is there anything in your user stylesheet that might be targeting file-icons?

Nope, is empty.

> Also, what other packages and themes do you have installed? Run apm list -ib at the terminal and show us the output.

packages: 
- linter + linter-eslint
- atom-beautify
- pigments

I am using following themes:
- atom-material-ui
- material-syntax

**Comment by Alhadis** [comment]
Does this issue vanish if you set your Atom directory to just `~/.atom`...?

**Comment by raphaelokon** [comment]
Hi @Alhadis. When I use the  `~/.atom` for my conf it works. Strange it doesn't work with a custom set config folder (via ENV)

```bash
### Custom Atom home
export ATOM_HOME="$HOME/path-to-atom-conf"
```

**Comment by Alhadis** [comment]
Erh, whereabouts are your packages installed? `~/.atom/packages/`...?

**Comment by raphaelokon** [comment]
Packages are installed under my `$ATOM_HOME/packages/` when I use my bespoke config, and are installed under `~/.atom/packages/` when I use standard config

**Comment by Alhadis** [comment]
Alright, let me guess... you have File-Icons installed in `~/.atom/packages`, right?

If so, the problem should be solved by moving (or symlinking) `~/.atom/packages/file-icons` to `$ATOM_HOME/packages/file-icons`.

**Comment by raphaelokon** [comment]
I had file-icons installed in both locations … but when I moved the `~/.atom/packages/file-icons` to `$ATOM_HOME/packages/file-icons` it suddenly worked …

**Comment by Alhadis** [comment]
Yeah, that's probably because you had an older version installed in the wrong directory. [This](https://github.com/DanBrooker/file-icons/blob/master/styles/fonts.less#L31) is the line pointing to the package's custom icon-font.

**Comment by Alhadis** [comment]
@raphaelokon If there are any further issues, please let me know. Otherwise, I'm assuming this is resolved.

**Comment by raphaelokon** [comment]
Cheers. All good now!
