### ISSUE TITLE
Icon request: Atom icon for ~/.atom folder

### ISSUE THREAD

**Issue by fusion809** [DanBrooker/file-icons#388]
Hi,

I have tried to do this myself in my own fork of this repo but I don't know what Less class name the Atom icon itself uses, if it even is defined. I'm surprised that no one has added an Atom icon for the `~/.atom` folder, as it seems like such an obvious one. 

Thanks for your time,
Brenton

**Comment by Alhadis** [comment]
Uh, dunno about you, but the number of times I've used Atom to open a folder which contains my `.atom` directory has been precisely zero, up until now.

Added.

**Comment by fusion809** [comment]
I do so fairly frequently. I've even uploaded my `~/.atom` folder to GitHub (https://github.com/fusion809/atom).

**Comment by Alhadis** [comment]
Eh, suit yourself. :p I have my Atom config files symlinked to a different repo. Tracking crap I haven't added feels like overkill.
