### ISSUE TITLE
Node modules icon is colored even when `on changes` is checked

### ISSUE THREAD

**Issue by michael-yx-wu** [DanBrooker/file-icons#390]
![screen shot 2016-06-16 at 11 57 12 am](https://cloud.githubusercontent.com/assets/3681045/16123604/9f5d7a5e-33b9-11e6-9803-e001ffbe795e.png)

I've made no changes to `node_modules` but the icon is still colored even though `on changes` is selected in settings.

**Comment by Alhadis** [comment]
Ah! I think only files are being targeted by that rule. Until recently, there weren't any folder icons that used colour, so it never came to mind.

Will fix.

**Comment by Alhadis** [comment]
Fixed, thanks for pointing that out! =)
