### ISSUE TITLE
npm-shrinkwrap.json

### ISSUE THREAD

**Issue by jacobmischka** [DanBrooker/file-icons#395]
I think it makes sense to give npm-shrinkwrap.json the same icon as package.json, given that it's a standard npm file.

https://docs.npmjs.com/cli/shrinkwrap

Thanks!

**Comment by Alhadis** [comment]
Haha, this was actually addressed in a [recent pull request](https://github.com/DanBrooker/file-icons/pull/393). =) It'll be shipped in the next release of the package.

**Comment by jacobmischka** [comment]
Oh, I searched in issues and didn't see it but I didn't look in PRs, nice.

**Comment by Alhadis** [comment]
You can always check the unpublished additions in the [changelog](https://github.com/DanBrooker/file-icons/blob/master/CHANGELOG.md); it's always at the top of the file.
