### ISSUE TITLE
Adding a Yeoman file icon for .yo-rc.json

### ISSUE THREAD

**Issue by zckrs** [DanBrooker/file-icons#396]
Hi,

First thank you for this useful and beautiful package.

Can you add a Yeoman file icon for .yo-rc.json ? Or how can I help you to achieve this goal ?

/cc @SBoudrias

**Comment by Alhadis** [comment]
Well, [there's this](https://github.com/Alhadis/DevOpicons/blob/master/svg/yeoman.svg). Are there any other filenames that should be using the Yeoman icon?

**Comment by zckrs** [comment]
As far as I know, nope.

**Comment by Alhadis** [comment]
Done.

**Comment by zckrs** [comment]
Thank you :+1:
