### ISSUE TITLE
'On Changes' option not working

### ISSUE THREAD

**Issue by miguelopezv** [DanBrooker/file-icons#398]
Using Atom 1.8.0, file-icons 1.7.15, OSX 10.11.5

On Changes option is selected, but after I make some changes to diferent files the icons on the Tree view remain B/W.

**Comment by Alhadis** [comment]
Is it a Git repository, or a normal folder?

**Comment by miguelopezv** [comment]
is a normal folder, on git folder the icon and the name of the file change to orange color.

**Comment by Alhadis** [comment]
Parcero, [pilla esto](https://github.com/DanBrooker/file-icons/issues/272).
