### ISSUE TITLE
Laravel icon problem

### ISSUE THREAD

**Issue by zaynali53** [DanBrooker/file-icons#400]
Laravel PHP icon is very small and also it's color is not correct. This is color used in laravel logo `#E74430`

#### Here is the sublime example

![sublime](https://cloud.githubusercontent.com/assets/8646770/16645613/bdd96b38-443e-11e6-8621-f9e6e7191b63.png)

#### Atom

![atom](https://cloud.githubusercontent.com/assets/8646770/16645616/c4243180-443e-11e6-98a7-e0ffc26e5895.png)

**Comment by Alhadis** [comment]
What icon package does Sublime use...?

I suppose an orangey-red is the appropriate colour to use, since it appears part of Laravel's branding...

**Comment by zaynali53** [comment]
I'm using [Material-Theme](https://github.com/equinusocio/material-theme), icons included.

And i picked this color from the [Laravel Website](https://laravel.com).

**Comment by Alhadis** [comment]
Right, well, with the way the package's colours are handled, the exact shade of orange can't be used. It'll need to be `#d28445`, which appears to be the closest match in the palette.

**Comment by zaynali53** [comment]
@Alhadis Ok sure. And icon size is too small. It should be the same as the rest

**Comment by Alhadis** [comment]
Yes, I'll patch that soon.

This is another example of why icon-font authors [should stop adding margins to their icons](https://github.com/Alhadis/DevOpicons#size-fixes).

**Comment by zaynali53** [comment]
@Alhadis Awesome. Thank you. I’m looking forward to it :)

**Comment by Alhadis** [comment]
This is difficult to fix in a manner that's compatible with all themes, so I'm limiting it to Atom Material only.

FYI, all size-related issues should be automatically fixed once [v2 is released](https://github.com/DanBrooker/file-icons/issues/359).

**Comment by zaynali53** [comment]
@Alhadis Awesome!. Thank you so much for your hardwork. :)
