### ISSUE TITLE
Color icons take on color of git status message in file tree

### ISSUE THREAD

**Issue by michael-yx-wu** [DanBrooker/file-icons#402]
When the `on change` setting is on, the icons assume the color of the git status of the file in the tree view (green for added, orange for modified) instead displaying their original colors. 

For example, in the attached screenshot, the icon for `code.svg` should be it's original orange-ish color instead of green and the icon for `compassIcon.svg` should be it's original blue color. 

<img width="168" alt="screen shot 2016-07-11 at 6 11 01 pm" src="https://cloud.githubusercontent.com/assets/3681045/16748562/d8f92190-4792-11e6-8705-4e8d9018e01c.png">

I'm not sure if this is possible to implement, but it would be really nice to see the original colors.

**Comment by Alhadis** [comment]
You mean like this...? =)

<img src="https://cloud.githubusercontent.com/assets/2346707/16748693/eabec422-4808-11e6-96a0-c5ae767d9186.png" width="161" alt="Figure 1" />

If so, don't worry, it'll be fixed in v2.

**Comment by michael-yx-wu** [comment]
Sort of. In your example, the markdown icons are all colored regardless of git status. When you have `on change` checked, I think it makes sense to keep non modified file icons black/grayed out and only show color icons for modified files. So in your screenshot, you'd expect contributing.md and new-file.txt to have color icons and the rest to be grayed out. Not sure if I'm explaining this very well...

**Comment by Alhadis** [comment]
Ah! No, I see what you mean. =)

I think it's safer to wait until v2 to sort this out. The last time I tampered with colours and repo-statuses, it caused a [Heisenbug](https://github.com/DanBrooker/file-icons/issues/352) which was impossible for me to reproduce... and I had no way of knowing how many other users were affected.

The package's stylesheets are a Jenga tower of rickety rules creaking under their own weight. I'd prefer not to poke them too much, if you know what I mean...

**Comment by michael-yx-wu** [comment]
That's fair. I'm happy to wait until the next major release. Just wanted to raise this issue in case you weren't aware :)

**Comment by Alhadis** [comment]
Thanks, mate. =) Will keep that in mind.
