### ISSUE TITLE
Add PostHTML/SugarML icon

### ISSUE THREAD

**Issue by michael-ciniawsky** [DanBrooker/file-icons#403]
hi, first thx for this awesome package, really appreciated.

Whats the appropriated path for adding/request adding an icon to file-icons. i read the CONTRIBUTING guide but not sure a to proceed.

We made a 'sugar syntax' (jade-ish) for posthtml, posthtml if unknown is similiar to want postcss is for css. The logo is in ```.svg```. 

Are there restrictions in terms of accepting new icons related to popularity of the tool?

**Comment by Alhadis** [comment]
Hrm, I'm not sure. @DanBrooker should answer this question.

As for the format, what file extension does your precompiler use?

**Comment by michael-ciniawsky** [comment]
@Alhadis you're fast :) 

> what file extension does your precompiler use?

You mean ```.ai``` or ```.ink``` etc? Why does this matter? Anyways i need to ask the creator :).

**Comment by DanBrooker** [comment]
@Alhadis is this a question of how we determine what icons to add? Is there a performance or maintenance cost we need to be considering.

**Comment by Alhadis** [comment]
No performance or maintenance cost, mate. Just curious if there's a criteria for notability, if any. =) Just realised I hadn't thought about it until now, haha.

@michael-ciniawsky It matters because if the extension conflicts with a "well-known" filetype, adding the icon won't do much good unless users configure their stylesheets to display the icon.

**Comment by Alhadis** [comment]
BTW, there *is* a slight performance concern with the Less-controlled approach we have now, but v2 will pretty much eradicate those issues.

**Comment by DanBrooker** [comment]
Hmm well my main motivation for this package was to help differentiate file types, so I think if an icon adds clarity then thats good, and bad if it makes things less clear.

So, I would think if people want less well known file extensions added then maybe submitting a PR should be a minimum.

**Comment by michael-ciniawsky** [comment]
@Alhadis the file extension would be  ```.phtml``` (html with posthtml), ```.sml```(html with sugarml-parser) and  ``.smg``(svg with sugarml-parser). To my knowledge none is used by other languages 

> maybe submitting a PR should be a minimum. 

@DanBrooker  Sure, but i need to get to it first

**Comment by Alhadis** [comment]
`.sml` is used by Standard ML, and there are [101,697](https://github.com/search?q=extension%3Asml+NOT+nothack&type=Code) results for that extension on GitHub. [`.smg`](https://github.com/search?q=extension%3Asmg+NOT+nothack&type=Code) seems okay, though.

`.phtml` is generally used for PHP templates, and there're over [4 million](https://github.com/search?q=extension%3Aphtml+NOT+nothack&type=Code) results with that extension.

**Comment by michael-ciniawsky** [comment]
😟 that's bad news thx for looking that up, ```.ssml``? is used approximately [2000](https://github.com/search?utf8=%E2%9C%93&q=extension%3Assml+NOT+nothack&type=Code&ref=searchresults) times, seems to be some other xml dialect

**Comment by Alhadis** [comment]
Hrm, why not use `.posthtml`?

**Comment by michael-ciniawsky** [comment]
it's an awfully long name :). the normal html5 icon is absolutely fine for plain posthtml html files, but the more urgent one is an icon for different syntax which should be visually recognizable somehow

uhh.. the naming nightmare 😄

**Comment by michael-ciniawsky** [comment]
```.smu``` maybe, thats [113](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asmu+NOT+nothack&type=Code&ref=searchresults) existing then, i have more html related on my machine :)

**Comment by Alhadis** [comment]
Honestly, I'd avoid any three-letter extension if it can be helped. Being specific protects your format from conflicts, even if it does look harder to type. Then again, the same criticism can be applied to any safe password, heh.

Even if there aren't many `.smu` files out in the wild now, you don't know if that's going to change in future...

**Comment by michael-ciniawsky** [comment]
@Alhadis sry for the delay i'm currently asking in the community what options we have and agree upon. Yeah you're definitely right. if it bothers you close the issue for now i file a new one when we agreed on the matter. Otherwise i came back here as soon as possible. Thanks for your patience until now 👍

**Comment by Alhadis** [comment]
All good, mate. =)
