### ISSUE TITLE
Use icon-mssql for .dsql rather than icon-database from mfizz

### ISSUE THREAD

**Issue by gontadu** [DanBrooker/file-icons#409]
This part I am missing a mapping that says something like

.dsql-icon             { .mf; content: "\fxxx"; left: 3px; }

I couldn't figure it out from the mfizz website, etc. BUT icon-mssql is more suitable than icon-database for the .dsql files as they are to my understanding, specific to Microsoft.

Do suggest where I can find the corresponding "\fxxx" and then its just changes in the icons.less and file-icons.less files.

**Comment by Alhadis** [comment]
It's `\f136`, mate. Mfizz change their codepoints with every new release of their font, making it impossible to specify a permanent index. But that's the codepoint being used by the Mfizz version bundled with this package.
