### ISSUE TITLE
Icon request for .pug-lintrc

### ISSUE THREAD

**Issue by azat-io** [DanBrooker/file-icons#410]
Hi!

Could you add some icon for `.pug-lintrc`, .`pug-lintrc.js`, and `.pug-lintrc.json` extensions of [Pug Linter](https://www.npmjs.com/package/pug-lint)?

**Comment by Alhadis** [comment]
Would the usual [Pug icon](https://github.com/Alhadis/FileIcons/blob/master/charmap.md#Pug) be enough?

**Comment by Alhadis** [comment]
Couldn't find anything else, so pup's face will have to do. =)

**Comment by azat-io** [comment]
Okay, thanks!
