### ISSUE TITLE
jinja2 support would be nice

### ISSUE THREAD

**Issue by profsmallpine** [DanBrooker/file-icons#412]
Add `&[data-name$=".jinja2"]:before         { .jinja-icon;             .dark-red; }` to styles -> file-icons.less:1011.

**Comment by Alhadis** [comment]
Done! I've used a different shade of red to help users differentiate between `.jinja` and `.jinja2` files, if that helps. :)

**Comment by profsmallpine** [comment]
@Alhadis awesome, thanks! I've been adding that line locally each time I update haha!

**Comment by Alhadis** [comment]
LOL dude, you should be [using your user stylesheet](https://github.com/DanBrooker/file-icons#customisation).

```less
@import "packages/file-icons/styles/items";
@{pane-tab-selector}, .icon-file-text {
	[data-name$=".jinja2"]:before { .jinja-icon; .dark-red; }
}
```

**Comment by profsmallpine** [comment]
@Alhadis There are too many things to know in the world, i can't keep track of it all 👍
