### ISSUE TITLE
Icon request for .tern-project

### ISSUE THREAD

**Issue by unluisco** [DanBrooker/file-icons#413]
I use [atom-ternjs](https://github.com/tststs/atom-ternjs) for autocomplete and need it a .tern-project file in directory.

Can you add an icon for that file?
Thanks!

**Comment by Alhadis** [comment]
Sure thing! ;) On it.

**Comment by Alhadis** [comment]
Are there any other Tern-related files we should be using this icon for?

**Comment by Alhadis** [comment]
Gonna take that as a no, heh.

YA ESTA PARCERO

**Comment by unluisco** [comment]
@Alhadis i was sleeping, but not, I don't know other tern-related file.
thanks for that!

**Comment by Alhadis** [comment]
DE NADA. ES UNA CHIMBAAAAAAA
