### ISSUE TITLE
Vala icon

### ISSUE THREAD

**Issue by handicraftsman** [DanBrooker/file-icons#415]

**Comment by Alhadis** [comment]
What's Vala?

**Comment by Alhadis** [comment]
Could you give us more information, please? What file types and file extensions does Vala use?

**Comment by Alhadis** [comment]
And what icon should it use?

![1923797_1136654403019151_8152796163044818049_n](https://cloud.githubusercontent.com/assets/2346707/17458215/4d499c30-5c4e-11e6-9774-9a4b7c960c16.jpg)

**Comment by handicraftsman** [comment]
Extension: .vala
Type: text/x-vala
Icon: IDK :smile:

**Comment by Alhadis** [comment]
We need an icon in order to add an icon.

Strange, but true.

**Comment by handicraftsman** [comment]
P. S. Khajitis are awesome
