### ISSUE TITLE
PHP icon is the Perl Icon?

### ISSUE THREAD

**Issue by jamieomaguire** [DanBrooker/file-icons#417]
All of my .php files are showing up as Perl files and I'm unsure as to why. I am running php through XAMPP, could this be the problem? 

Thanks
![screenshot](https://cloud.githubusercontent.com/assets/16766185/17547563/cbe9fcfe-5edf-11e6-8744-c3bd9c245ab9.png)

**Comment by Alhadis** [comment]
Ah no, that's not the Perl icon... that's the icon used for PHP files. Different animal:

<img alt="Perl" src="https://camo.githubusercontent.com/6b27cc37266706387d7f8611993f67552c46b352/68747470733a2f2f63646e2e7261776769742e636f6d2f416c68616469732f4d466978782f6d61737465722f7376672f7065726c2e737667" width="110" />      <img alt="PHP" src="https://camo.githubusercontent.com/040ddc856923addf4e367aa6b3c2c7760cb2f8e7/68747470733a2f2f63646e2e7261776769742e636f6d2f416c68616469732f46696c6549636f6e732f6d61737465722f7376672f5048502e737667" width="120" />

It's possible you might've been mislead by the readme file's image, which is outdated. If you prefer the shield icon, just add this to your user stylesheet:

```css
.icon-file-text[data-name$=".php"]:before{
	font-family: "FontMfizz" !important;
}
```
