### ISSUE TITLE
menu bug

### ISSUE THREAD

**Issue by rzubrycki** [DanBrooker/file-icons#419]
Hi, on left hand side menu icons are not showing up. On tab panel its fine.
What can be the issue?

**Comment by Alhadis** [comment]
Well, you haven't given us very much to go by...

Can you include a screenshot?

**Comment by Alhadis** [comment]
It would also help us if you told us what themes and packages you have installed, so we can help pinpoint the issue...

**Comment by Alhadis** [comment]
@rzubrycki We're still waiting on your input.

**Comment by Alhadis** [comment]
I'm closing this as a non-issue. From your brief description, it sounds like you're using Seti UI. See [here for a description of the simple fix](https://github.com/DanBrooker/file-icons/issues/420).

If this is a different issue, then please provide adequate details. Thank you.
