### ISSUE TITLE
Icons mismatch despite restart

### ISSUE THREAD

**Issue by beingmrkenny** [DanBrooker/file-icons#420]
I'm finding certain icons are still incorrect despite restarting.

Generally file tree is correct, but the tab icons are not. (Please excuse paranoid filename blurring, this is a work repo, don't want to get in trouble).

Changing themes doesn't seem to remedy the issue.

![icons](https://cloud.githubusercontent.com/assets/2005857/18173321/1ae48468-7061-11e6-8411-61b4e6dd60db.png)

Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

OS X 10.11.6

All packages and themes are up to date

├── Sublime-Style-Column-Selection@1.7.2
├── auto-update-packages@1.0.1
├── block-comment-plus@0.4.0
├── css-comb@2.5.0
├── daylight-ui@0.2.2
├── file-icons@1.7.19
├── file-types@0.5.4-p1
├── highlight-selected@0.11.2
├── pigments@0.34.0
├── remove-whitespace@0.2.1
├── seti-ui@1.3.2 (current ui theme)
├── yeti-syntax@0.1.2
└── yeti-ui@0.1.6

Syntax theme: One Light

**Comment by Alhadis** [comment]
Have you disabled Seti UI's **Custom Icons* setting...?

<img width="662" alt="Figure 1" src="https://cloud.githubusercontent.com/assets/2346707/18188833/aabf3d52-70f8-11e6-88df-1190252a3626.png" />

The UI theme has a setting to disable custom icons for users of other icon packages.

**Comment by beingmrkenny** [comment]
That sorted it, thanks.
