### ISSUE TITLE
File Icons not loading 

### ISSUE THREAD

**Issue by sgsvenkatesh** [DanBrooker/file-icons#423]
The file icons don't load sometimes, most probably whenever a new package is being installed.

This is how it looks like when the icons don't load.

![image](https://cloud.githubusercontent.com/assets/4642729/18660021/e07a10a2-7f2b-11e6-83c9-c94ac238d3ef.png)

An immediate restart doesn't fix this but a restart after a while does.

**Comment by Alhadis** [comment]
Can you run `apm ls -i` in your terminal and copy the output to [PasteBin.com](http://pastebin.com/)?

**Comment by sgsvenkatesh** [comment]
This is the output for `apm ls -i`
```
apm ls -i
Community Packages (19) /Users/myusername/.atom/packages
├── angularjs@0.3.5
├── atom-beautify@0.29.12
├── auto-update-packages@1.0.1
├── autoclose-html@0.23.0
├── autocomplete-modules@1.6.3
├── docblockr@0.8.5
├── emmet@2.4.3
├── expand-region@0.2.4
├── file-icons@1.7.19
├── hyperclick@0.0.38
├── intellij-idea-keymap@0.2.1
├── javascript-snippets@1.2.1
├── js-hyperclick@1.5.0
├── js-refactor@0.7.3
├── last-cursor-position@0.9.0
├── multi-cursor@2.1.3
├── next-line-comment@0.2.1
├── pigments@0.34.0
└── refactor@0.9.2

└── (empty)
```

**Comment by Alhadis** [comment]
Does this happen often? Or whenever something updates?

When it does, you might find a console or network error in the devtools. Go <kbd>View -> Developer -> Developer Tools</kbd> and check the Network tab. You should also check what font is being assigned to the boxes (as a theme or package might've reassigned it to something else).

**Comment by sgsvenkatesh** [comment]
Only when something is updating and it gets resolved by itself.

When I see this issue again, I'll update it here with the info from developer tools.

**Comment by sgsvenkatesh** [comment]
@Alhadis I'm not using any themes. This is what I see inspecting the icons. It is using Octicons Regular font. 

<img width="279" alt="screen shot 2016-09-25 at 8 38 30 pm" src="https://cloud.githubusercontent.com/assets/4642729/18816115/19f14476-8360-11e6-9ee3-955cb8d7d102.png">

**Comment by sgsvenkatesh** [comment]
@Alhadis Any idea of this issue? This is still happening even after Atom's recent update.

**Comment by Alhadis** [comment]
Ah sorry, I meant to get back to this...

When this happens, can you run the following code in your dev-console and paste the result here?

```js
copy(Array.from(document.querySelectorAll("style")).map(s => s.parentElement.tagName + ": " + s.getAttribute("source-path")).join("\n"));
```

It'll automatically copy it to your clipboard.

**Comment by sgsvenkatesh** [comment]
Here is the output.

`ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/static/atom.less
ATOM-STYLES: global-text-editor-styles
ATOM-STYLES: /Users/myusername/.atom/packages/angularjs/styles/angularjs.less
ATOM-STYLES: /Users/myusername/.atom/packages/autoclose-html/styles/autoclose-html.less
ATOM-STYLES: /Users/myusername/.atom/packages/emmet/styles/emmet.less
ATOM-STYLES: /Users/myusername/.atom/packages/file-icons/styles/colors.less
ATOM-STYLES: /Users/myusername/.atom/packages/file-icons/styles/file-icons.less
ATOM-STYLES: /Users/myusername/.atom/packages/file-icons/styles/fonts.less
ATOM-STYLES: /Users/myusername/.atom/packages/file-icons/styles/icons.less
ATOM-STYLES: /Users/myusername/.atom/packages/file-icons/styles/items.less
ATOM-STYLES: /Users/myusername/.atom/packages/hyperclick/styles/hyperclick.less
ATOM-STYLES: /Users/myusername/.atom/packages/js-refactor/styles/js-refactor.less
ATOM-STYLES: /Users/myusername/.atom/packages/pigments/styles/pigments.less
ATOM-STYLES: /Users/myusername/.atom/packages/pigments/styles/themes.less
ATOM-STYLES: /Users/myusername/.atom/packages/refactor/styles/refactor.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/about/styles/about.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/about/styles/variables.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/archive-view/styles/archive-view.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/styles/autocomplete.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/styles/background-tips.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/bookmarks/styles/bookmarks.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/styles/bracket-matcher.atom-text-editor.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/deprecation-cop/styles/deprecation-cop.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/encoding-selector/styles/encoding-selector.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/styles/fuzzy-finder.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/git-diff/styles/git-diff.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/grammar-selector/styles/grammar-selector.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/image-view/styles/image-view.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/incompatible-packages/styles/incompatible-packages.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/keybinding-resolver/styles/keybinding-resolver.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/styles/markdown-preview-default.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/styles/markdown-preview-github.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/styles/markdown-preview.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/notifications/styles/notifications.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/styles/package-card.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/styles/package-readme.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/styles/settings-view.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/styles/variables.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/spell-check/styles/spell-check.atom-text-editor.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/styles/status-bar.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/styleguide/styles/components.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/styleguide/styles/styleguide.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/styleguide/styles/variables.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/tabs/styles/layout.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/tabs/styles/tabs.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/timecop/styles/timecop.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/styles/tree-view.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/stylesheets/select-list.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/welcome/styles/welcome.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/wrap-guide/styles/wrap-guide.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/one-dark-syntax/index.less
ATOM-STYLES: /Users/myusername/Documents/Installations/Atom.app/Contents/Resources/app.asar/node_modules/one-dark-ui/index.less
ATOM-STYLES: /Users/myusername/.atom/styles.less`

**Comment by Alhadis** [comment]
Is this happening right now? Like, were the icons still missing when you executed that code?

**Comment by sgsvenkatesh** [comment]
Looks like [refactor](https://github.com/hax/js-refactor/issues/16) package is causing the issue like mentioned in this [comment](https://github.com/DanBrooker/file-icons/issues/416#issuecomment-238906290).

**Comment by Alhadis** [comment]
Ugh, that again... :S

Alright, well, that would explain the weird on-and-off. I'll close this issue as unrelated to this package, but `refactor`'s maintainer *really* needs to look into this... because it's incredibly confusing.

**Comment by Alhadis** [comment]
@sgsvenkatesh Think I figured out what's been going on here. Have [submitted a pull request](https://github.com/hax/refactor/pull/28), but as you'll read in its description, I can't guarantee it *will* fix this weird bug with the refactor package.

**Comment by sgsvenkatesh** [comment]
@Alhadis Thanks. Hope it fixes the issue. For the moment, using this as a [temporary solution](https://github.com/hax/js-refactor/issues/16#issuecomment-246653469).

**Comment by Alhadis** [comment]
I'm hoping the author actually bothers looking at it...
