### ISSUE TITLE
what is going on?

### ISSUE THREAD

**Issue by liuchangxing** [DanBrooker/file-icons#425]
![qq 20160922221327](https://cloud.githubusercontent.com/assets/22342099/18751661/5c632978-8112-11e6-9605-b09ca20efa6a.png)
Why?

**Comment by Alhadis** [comment]
1. **What themes and packages do you have installed?**
Run `apm ls -i` and copy the output.

2. **What CSS `font-family` is being applied to the icons?**
Open the devtools and inspect the broken icon.<br/><br/>You should see something like this in the bottom-right corner:
<img src="https://cloud.githubusercontent.com/assets/2346707/18751968/409e88f6-8124-11e6-9484-5fae7d6267e7.png" width="543" alt="Figure 1" />

3. **Does your user stylesheet have any rules that might be affecting the icon?**
If so, open your stylesheet and copy+paste the relevant CSS.

**Comment by liuchangxing** [comment]
My is Windows 7 system.

**Comment by Alhadis** [comment]
That tells us nothing.

Okay, open up your devtools, and enter this in the console.

```js
copy(Object.keys(atom.packages.activePackages).sort().join("\n"))
```

Paste the output here.

**Comment by liuchangxing** [comment]
I can only run the NPM.
Is that right.
![qq 20160924152123](https://cloud.githubusercontent.com/assets/22342099/18806824/9bbfc7f8-826a-11e6-8fee-e9eb9d900513.png)

**Comment by liuchangxing** [comment]
Is that right?

**Comment by Alhadis** [comment]
No. **In Atom.**

1. Press <kbd>Ctrl+Alt-+i</kbd>
2. Click "Console" in the top-right corner
3. Run `copy(Object.keys(atom.packages.activePackages).sort().join("\n"))`
4. What does it say?

**Comment by liuchangxing** [comment]
![qq 20160924152803](https://cloud.githubusercontent.com/assets/22342099/18806867/88032114-826b-11e6-9de3-8c955828b1d3.png)
Click Where?

**Comment by liuchangxing** [comment]
"about
activate-power-mode
archive-view
atom-beautify
autocomplete-atom-api
autocomplete-css
autocomplete-html
autocomplete-plus
autocomplete-snippets
autosave
background-tips
bookmarks
bracket-matcher
colorful-cursor
deprecation-cop
dev-live-reload
encoding-selector
exception-reporting
fonts
fuzzy-finder
git-diff
glowing-cursor
grammar-selector
grammar-tab-colors
image-view
incompatible-packages
keybinding-resolver
language-c
language-clojure
language-coffee-script
language-csharp
language-css
language-gfm
language-git
language-go
language-html
language-hyperlink
language-java
language-javascript
language-json
language-less
language-make
language-mustache
language-objective-c
language-perl
language-php
language-property-list
language-python
language-ruby
language-ruby-on-rails
language-sass
language-shellscript
language-source
language-sql
language-text
language-todo
language-toml
language-xml
language-yaml
line-ending-selector
markdown-preview
metrics
minimap
minimap-autohide
neon-selection
notifications
one-dark-ui
one-light-syntax
seti-icons
settings-view
simplified-chinese-menu
snippets
spell-check
status-bar
styleguide
tabs
timecop
tree-view
update-package-dependencies
welcome
whitespace
wrap-guide"

**Comment by liuchangxing** [comment]
I found it.

**Comment by Alhadis** [comment]
You haven't installed this package.

**To install this package:**
1. Open Atom's Settings
2. Click on **+ Install** at the bottom
3. Search for `File Icons` and click "Install"

If you download this package as a ZIP folder, it will NOT work. The package must be installed through the control panel.

Also, you have `seti-icons` installed. This conflicts with `file-icons`, there is no need for both.

Also, you are trying to install

**Comment by liuchangxing** [comment]
Wait a minute

**Comment by liuchangxing** [comment]
![qq 20160924154603](https://cloud.githubusercontent.com/assets/22342099/18806950/141bc546-826e-11e6-820a-e793c001442d.png)
I only have a right now.

**Comment by liuchangxing** [comment]
No use,

**Comment by Alhadis** [comment]
This is frustrating. 👍 

1. If you have `seti-icons` installed, uninstall it
2. If you have `seti-ui` theme enabled, disable its `Custom Icons` setting:
<img src="https://cloud.githubusercontent.com/assets/2346707/18188833/aabf3d52-70f8-11e6-88df-1190252a3626.png" width="600" />

Otherwise, I can't be of help beyond this. I can sense there's a language barrier here.

**Comment by liuchangxing** [comment]
I'm sorry, my English is not good

**Comment by Alhadis** [comment]
It's better than my Cantonese.

**Comment by liuchangxing** [comment]
![qq 20160924160343](https://cloud.githubusercontent.com/assets/22342099/18807067/82990144-8270-11e6-9658-4ab9608cab95.png)
I don't have that theme.

**Comment by liuchangxing** [comment]
![qq 20160924160822](https://cloud.githubusercontent.com/assets/22342099/18807084/2de0bcea-8271-11e6-86ea-83b0841012a9.png)
I don't have to install this

**Comment by Alhadis** [comment]
You can try disabling [`fonts`](https://atom.io/packages/fonts) and see if that makes a difference.

Otherwise, I don't know.

**Comment by liuchangxing** [comment]
In fact, I quite like to talk with foreigners

**Comment by liuchangxing** [comment]
![qq 20160924161120](https://cloud.githubusercontent.com/assets/22342099/18807102/99546b70-8271-11e6-886f-bff01fe0c069.png)
Disable this?

**Comment by Alhadis** [comment]
Yes. Otherwise, the only other thing I can think of is that the `simplified-chinese-menu` package is hiding the file icons.

Sorry.

**Comment by liuchangxing** [comment]
No, this is localization of ATOM plug-in for Chinese

**Comment by liuchangxing** [comment]
The plug-in can be translated into Chinese

**Comment by Alhadis** [comment]
<img src="https://cloud.githubusercontent.com/assets/2346707/18807462/2c3c11b8-828b-11e6-80c2-333f3f253d59.jpg" width="400" />

**Comment by liuchangxing** [comment]
I found that you are interesting.

**Comment by Alhadis** [comment]
I noticed that myself a long time ago.

**Comment by liuchangxing** [comment]
And then?

**Comment by liuchangxing** [comment]
I want to see what's it like in your hometown.

**Comment by Alhadis** [comment]
Alright, enough now. Every time a comment is posted, 11 people get e-mail notifications.
