### ISSUE TITLE
User styles.less overrides conflicting with theme variables?

### ISSUE THREAD

**Issue by kmck** [DanBrooker/file-icons#426]
Hi there! Love this plugin. I'm trying to add a custom file type icon by adding this to my user `styles.less`:

```less
@import "packages/file-icons/styles/icons";
@import "packages/file-icons/styles/colors";
@import "packages/file-icons/styles/items";
@{pane-tab-selector},
.icon-file-text {
  &[data-name$=".mjs"]::before {
    .jsx-icon;
    .medium-yellow;
  }
}
```

Works totally great, except I have some other user styles that are relying on theme variables for consistency, and as soon as I import icons or colors, it seems to reset the values of a bunch of standard variables (eg. `@text-color` and `@background-color-error`).

After some poking around, I've determined that it's something to do with `@import "ui-variables";` happening in those files. Any idea how I can over-override `ui-variables`with the theme variables that I intend to use?

**Comment by kmck** [comment]
On further investigation, it seems that the problem is that the custom stylesheet was inheriting those values from who-knows-where and that I should have been importing `ui-variables` and `syntax-variables` to get the right values in the first place. Nevermind!

**Comment by Alhadis** [comment]
FWIW, [v2](https://github.com/DanBrooker/file-icons/issues/359) will make this a lot easier. =)
