### ISSUE TITLE
'on changes' and 'tab pane icons'

### ISSUE THREAD

**Issue by naldir** [DanBrooker/file-icons#429]
The tab `pane icons` option does not apply colours on tabs as it should when used with `on changes` option

![capture du 2016-10-05 14-55-46](https://cloud.githubusercontent.com/assets/6940236/19113868/d4bad72e-8b0b-11e6-9e65-446d961998c3.png)
![capture du 2016-10-05 14-55-09](https://cloud.githubusercontent.com/assets/6940236/19113869/d4c288e8-8b0b-11e6-9b7a-d6d81c3d6a07.png)

however as you can see on the screenshots the icon of the edited `README.md` is not of the same color than the text in contrary of `newfile.py` whose text and icon are the same color.

**Comment by Alhadis** [comment]
The [`tabs`](https://github.com/atom/tabs) package isn't adding CSS classes to indicate a file's VCS status... which it *should* be doing. :| I just realised this is a bug in the `tabs` package and should be fixed.

Thanks for pointing this out! I'll prepare a pull-request to get this fixed. Unfortunately, there's little we can do about it before then... sorry!
