### ISSUE TITLE
Icon request for wercker.yml

### ISSUE THREAD

**Issue by EliasJorgensen** [DanBrooker/file-icons#432]
Hi!

I'm using [Wercker](http://wercker.com/), which uses the `wercker.yml` file, as CI/CD service for my project, would it be possible for you to add an icon for that?

Thanks! :smiley:

**Comment by Alhadis** [comment]
Hey Elias, no problem! Is that the only filename we need to be checking for?

**Comment by EliasJorgensen** [comment]
Awesome!
I've been looking through the docs, and i haven't found any other filenames, besides `wercker.yml`. 😄

**Comment by Alhadis** [comment]
Done! Sorry that took so long.
