### ISSUE TITLE
New Icon For Groovy

### ISSUE THREAD

**Issue by alvartabe** [DanBrooker/file-icons#433]
Hello, this is not an issue, but can anyone please create an icon for Groovy Language.
Also I would like to thank to all contributors for this plugin.

**Comment by Alhadis** [comment]
What's wrong with the old one?

**Comment by Alhadis** [comment]
@alvartabe There's already an icon for Groovy, so perhaps you didn't notice it. Groovy's logo *is* pretty detailed, so I can't blame you for not recognising it:

<img src="https://cloud.githubusercontent.com/assets/2346707/19597727/0ad4c71a-97e2-11e6-91b4-a9df28511f79.png" alt="Figure 1" />

If you have a request for a different icon, please submit a new issue. Thank you.
