### ISSUE TITLE
Less icon: why the same as the CSS one?

### ISSUE THREAD

**Issue by JonGarbayo** [DanBrooker/file-icons#434]
Hi guy.

First of all, thanks for your great package, Atom is really more good looking with it! :)

But I don't really know/understand why the CSS and the Less icons are the same, the Less one being just a little darker. Could you explain it? Or better, can you change the Less icon with the Less logo :)?

Thanks for reading!

**Comment by Alhadis** [comment]
[This would be why](https://github.com/DanBrooker/file-icons/pull/371#issuecomment-220987151).

Horrible logo, details lost at icon-size, and overall just not recognisable...

**Comment by JonGarbayo** [comment]
OK, I understand now :x

Isn't it possible to get just the l of the Less logo?
Something like: 

{l}

instead of:

{less}

?

**Comment by Alhadis** [comment]
I already tried that, and it wasn't really recognisable...

<img src="https://cloud.githubusercontent.com/assets/2346707/19301930/b8d86164-90ad-11e6-8169-4f93f3498fcc.png" width="128" alt="Less" /> <img src="https://cloud.githubusercontent.com/assets/2346707/19301930/b8d86164-90ad-11e6-8169-4f93f3498fcc.png" width="16" alt="Less" />

**Comment by Alhadis** [comment]
Sorry. You can always ask the Less guys to improve their logo. :D
