### ISSUE TITLE
Icons also for folders.

### ISSUE THREAD

**Issue by balazsorban44** [DanBrooker/file-icons#438]
Would it be possible, to extend the file icons to folders which has the same name too? Like a folder called SASS also has the SASS icon for example.

**Comment by Alhadis** [comment]
Possible, yes, but I imagine that would go against a lot of user expectations. It would make the tree-view look confusing to see folder icons replaced with file icons.

**Comment by balazsorban44** [comment]
Okay, so I should only do it locally then.

**Comment by Alhadis** [comment]
Yes. That's why we use CSS. =)

**Comment by balazsorban44** [comment]
Or make it optional?

**Comment by Alhadis** [comment]
No, I think it's too niche a feature. Plus the stylesheet is already very complicated, and having all those rules apply to folders as well would likely impose maintenance issues.
