### ISSUE TITLE
PHP file icon missing

### ISSUE THREAD

**Issue by emzian** [DanBrooker/file-icons#444]
after updating the php file icon has gone missing. icons works for other file types.

![image](https://cloud.githubusercontent.com/assets/12171913/19625971/8b9defa8-9944-11e6-85ce-ed51a4f7d90e.png)

**Comment by Alhadis** [comment]
You installed the wrong package. ;-) Try uninstalling [`file-type-icons`](https://atom.io/packages/file-type-icons) and make sure you installed [`file-icons`](https://atom.io/packages/file-icons) instead.

Don't worry, you're not the first person to make that mistake.

**Comment by Alhadis** [comment]
If you're still seeing weirdness, try closing and restarting Atom. That often works.
