### ISSUE TITLE
One more icon request

### ISSUE THREAD

**Issue by azat-io** [DanBrooker/file-icons#445]
[Lint Staged](https://www.npmjs.com/package/lint-staged) config files:

* `.lintstagedrc` file in JSON or YML format
* `lint-staged.config.js` file in JS format

**Comment by Alhadis** [comment]
What icon should they use? Does Lint Staged have a logo?

**Comment by azat-io** [comment]
@okonet ^

**Comment by okonet** [comment]
No, it doesn't have a logo at this moment.

But this is the "standard" configuration file Babel, ESLint and many others are using.

**Comment by Alhadis** [comment]
My local copy of the package is a mess at the moment (performing a dissection of V2 components, ripping useful stuff out and rewriting it so it's actually maintainable), so... assuming I don't get to this in the near future, somebody else can submit a pull request for it. =)

I imagine `. lintstagedrc` can just be assigned the generic gear icon.

**Comment by okonet** [comment]
Yes, gear is good IMO.

**Comment by ajotaos** [comment]
Could this add the other variants for `.lintstagedrc` that are supported? https://www.npmjs.com/package/lint-staged#configuration
