### ISSUE TITLE
Custom folders color

### ISSUE THREAD

**Issue by radiocity** [DanBrooker/file-icons#446]
Hi. First of all, thank you for a greatest plugin ever.

Is it possible to force some folders/files icons to be colored with custom color? It will help to make accent on it.

**Comment by Alhadis** [comment]
Yes. The steps are [documented in the readme](https://github.com/DanBrooker/file-icons#customisation).

Just replace `&[data-name=".git"]` with `&[data-name$="your-folder-name"] and assign the colours in your user stylesheet.

**Comment by radiocity** [comment]
Thank you. 
IMHO, it would be great to change icon color throw context menu (right click)

**Comment by Alhadis** [comment]
Uh, no, that would be going way too far. That's the responsibility of a stylesheet. :-)
