### ISSUE TITLE
Icon request: Snyk

### ISSUE THREAD

**Issue by Alaneor** [DanBrooker/file-icons#448]
Here's an icon I would love to see added to this already excellent and exhaustive icon set: [snyk.io](https://snyk.io).

Target filename: `.snyk`

They have a nice SVG at their homepage, perhaps it would be helpful in generating the font icon. Attaching it here just in case.

[snyk-dog.svg.zip](https://github.com/DanBrooker/file-icons/files/555518/snyk-dog.svg.zip)

Preview:
![snyk](https://cloud.githubusercontent.com/assets/3058150/19764248/59e1657a-9c42-11e6-963f-2fe6250e8784.png)

Thanks!

**Comment by Alhadis** [comment]
Yikes. I'll see what I can do, but the details that make the image recognisable will probably be lost at icon-size...

**Comment by Alaneor** [comment]
Ah, you are probably right... Well thanks for giving it a shot anyway! Always appreciated.

**Comment by Alhadis** [comment]
The shield will have to go, I think. It's what's making it hard for the icon to not look Batman-related...

**Comment by Alhadis** [comment]
Hrm, how's this?

<img src="https://cloud.githubusercontent.com/assets/2346707/19765102/5c720a60-9c92-11e6-8b10-3d85a2b180ab.png" width="200" />

<img src="https://cloud.githubusercontent.com/assets/2346707/19765102/5c720a60-9c92-11e6-8b10-3d85a2b180ab.png" height="15" /> ← Rough approximation of how it'll look shrunk-down

**Comment by Alaneor** [comment]
You were right that most of the details will be gone, although I think that people who use Snyk in their apps will immediately recognise the icon anyway, especially if its colour will be similar to that of the original image.

So 👍 !

**Comment by Alhadis** [comment]
Done, mate. =)

I'm really digging the combination of recent additions, BTW:

<table>
	<tr>
		<td align="center" width="100"><img src="https://camo.githubusercontent.com/0b6f807796eeb13546a0a2cbfca038ce41a762e4/68747470733a2f2f63646e2e7261776769742e636f6d2f416c68616469732f46696c6549636f6e732f6d61737465722f7376672f5961726e2e737667" height="64" /></td>
		<td align="center" width="100"><img src="https://camo.githubusercontent.com/90c10904853ad2e92b402d3508b0392b23913ff5/68747470733a2f2f63646e2e7261776769742e636f6d2f416c68616469732f46696c6549636f6e732f6d61737465722f7376672f456469746f72436f6e6669672e737667" height="64" /></td>
		<td align="center" width="100"><img src="https://camo.githubusercontent.com/b682c9bf1a8710edd0afbd5e096127796ddf98b8/68747470733a2f2f63646e2e7261776769742e636f6d2f416c68616469732f46696c6549636f6e732f6d61737465722f7376672f536e796b2e737667" height="64" /></td>
	</tr>
	<tr align="center">
		<td><b>Cat</b></td>
		<td><b>Mouse</b></td>
		<td><b>Dog</b></td>
	</tr>
</table>

We're missing a canary, goldfish and carpet python.

**Comment by Alaneor** [comment]
Haha, nice. 😄 Thanks for the addition, looking forward to seeing it live!
