### ISSUE TITLE
Add icon for NSIS files

### ISSUE THREAD

**Issue by idleberg** [DanBrooker/file-icons#452]
We're currently in preparation to roll out the new NSIS logo on large scale (it's already used in various places, e.g. [GitHub](https://github.com/NSIS-Dev/) and [Twitter](https://twitter.com/nsis_tweets)), and as a user of your package, I would love to the existing logo replaced with the new one.

You can find an SVG image for low-resolutions in the [logo repository](https://github.com/idleberg/nsis-logo-v3/blob/master/src/Logo/below%2048x48/mono-flat.svg). As color I suggest `#867991` since it's the median of the gradient that we'll using in the branding.

**Comment by Alhadis** [comment]
Done! This is how it'll look:

<img src="https://cloud.githubusercontent.com/assets/2346707/19852939/5b449100-9fba-11e6-86e0-5321df8350df.png" width="143" alt="Preview" />

That shade of purple is the closest colour matching the one you've given, so I hope that's suitable. :)

Will amend to the package's stylesheet before the next release (can't do it now, as I'm in the middle of development on a different branch, heh).

Thanks!

**Comment by idleberg** [comment]
Thanks for the quick inclusion. The purple is fine with me!

**Comment by idleberg** [comment]
Sorry for reopening this. May I suggest an edit for the icon? I've based the attached file on the [new template](https://github.com/idleberg/nsis-logo-v3/tree/master/src/Logo/below%2024x24) for icons below 24x24.

**SVG File**:

[nsis-icon.zip](https://github.com/DanBrooker/file-icons/files/591372/nsis-icon.zip)

Ideally, this looks more crisp, like in the mockup below

**Preview**:

![screen shot 2016-11-15 at 09 18 09](https://cloud.githubusercontent.com/assets/1504938/20298201/d1f35f60-ab14-11e6-9cd0-400cfc743d5d.png)

**Comment by Alhadis** [comment]
Absolutely no problem at all, mate. Will update the icon soon-ish. ;)

I can't say when it'll be released... I'm kinda hoping [v1.7.25](https://github.com/DanBrooker/file-icons/releases/tag/v1.7.25) will be the last v1.*.* release until v2.0.0. Which is due to be a nice Christmas present for the Atom community. :)

**Comment by Alhadis** [comment]
Sorry about the slow response, mate. =)

I've amended the new NSIS icon to use the clearer version. Will be visible in the next release. Thanks!
