### ISSUE TITLE
Icon request: Codecov

### ISSUE THREAD

**Issue by EliasJorgensen** [DanBrooker/file-icons#453]
Hey, would it be possible to add an icon for the codecov.yml file?

Thanks! :smile:

**Comment by Alhadis** [comment]
Easy. :) Give me 10 minutes.

**Comment by EliasJorgensen** [comment]
Awesome! Thanks for the quick reply! :+1:

**Comment by Alhadis** [comment]
Took a moment to clean up the icon's geometry... managed to golf it down to 11 points (from the 63 points that the site's icon has; that's about ~17% the size/complexity of the original, heh).

Can't push a change to this package's master branch yet, but will do so before the next release. =) This is how it'll look:

<img src="https://cloud.githubusercontent.com/assets/2346707/19855844/c6064352-9fca-11e6-9c88-324648b2deb6.png" width="268" alt="Figure 1" />
