### ISSUE TITLE
Question: Is 3945ms of additional load time from this plugin normal?

### ISSUE THREAD

**Issue by flyinbutrs** [DanBrooker/file-icons#454]
I'm going through my package list, trying to figure out what is making Atom so slow to start for me, and I see this plugin is adding 3945ms:

![image](https://cloud.githubusercontent.com/assets/1248221/19930847/99e72aea-a0e0-11e6-8c78-25c1600f09db.png)

Is that normal? If so, can anything be done to speed it up? If not, any ideas on how I can debug this?

**Comment by flyinbutrs** [comment]
Just read the task list on #359, I suspect increasing load time is on the to-do. If the above is totally normal, I can just close this.

**Comment by Alhadis** [comment]
Hey there,

Does this happen on reboot? Double-check that you're not running in development mode or anything.

There's no way it should be taking *that* long.

**Comment by Alhadis** [comment]
Average load time for v2 is ~35-45ms, BTW.

**Comment by Alhadis** [comment]
@flyinbutrs Any feedback? Is this still happening?

**Comment by flyinbutrs** [comment]
After a reboot, it's a much mroe reasonable 171ms. I'm also still on 1.7.25 though. Is v2 out?

**Comment by Alhadis** [comment]
Ah no, not yet. Still about 45-50% through, but it's going well. I've made it a mission to release V2 before Christmas, though, hahaha. I opened a [project board-thingie](https://github.com/DanBrooker/file-icons/projects/1) for it.

Glad to hear the speed was only a temporary issue. :-) Ping me again if you see anything unusual.
