### ISSUE TITLE
icon request: UnixExecutables

### ISSUE THREAD

**Issue by unluisco** [DanBrooker/file-icons#455]
I am writing some Go code, but the builds have a simple icon
![settings users luisco dropbox dev go 2016-11-04 15-09-04](https://cloud.githubusercontent.com/assets/6332263/20020861/573c06c6-a2a1-11e6-9028-caca37fdded3.png)
this is the icon in finder:
![bin 2016-11-04 15-12-42](https://cloud.githubusercontent.com/assets/6332263/20020877/675d0ffa-a2a1-11e6-8ab1-7e36f9ad8ef0.png)
Thanks!

**Comment by Alhadis** [comment]
[Will be addressed in v2](https://github.com/DanBrooker/file-icons/issues/359).
