### ISSUE TITLE
No icon mapped to .xhtml files.

### ISSUE THREAD

**Issue by garretwilson** [DanBrooker/file-icons#460]
Someone seems to have forgotten to map an icon to the `.xhtml` extension. As you know, this is a popular extension not only for XHTML 1.x files, but also for HTML5 files that are also XML compliant. See discussion of "XHTML 5" at https://www.w3.org/TR/html5/introduction.html#html-vs-xhtml .

If someone could map some sort of HTML icon to `.xhtml` files I would appreciate it. If no one has time, I'll look into the source code if I can get a minute free in the future.

**Comment by icflorescu** [comment]
If no one else steps it, I could do it, but I have a quick question: would you map this to the HTML5 or the XML icon?
Personally, I'd lean towards XML...

**Comment by garretwilson** [comment]
No, please don't map it to XML. Why would you do that?

All HTML5 documents are also text documents. But we don't map them to the "text document" icon. We want an icon showing that they are a special format with special rules with special semantics---specifically HTML semantics.

Similarly this is not just any old XML file. There are gazillions of types of XML files. These `.xhtml` files are 99% no different than your `.html` files, except _they are following stricter rules_ (such as the requirement of ending tags). This does not keep them from being HTML files. In fact XHTML files are governed by the HTML5 specification just like non-XML HTML files --- I gave the link in the description.

Not only that, many such `.xhtml` files are so-called "polyglot" X/HTML5 files, which mean that they you could change the extension from `.xhtml` to `.html` and a non-XML-aware HTML parser could process them with zero problems.

Please leave the "XML" icon to the `.xml` extension, just as we use the "Text" icon for `.txt` files and not for `.html` files. Thank you.

**Comment by icflorescu** [comment]
I see what you mean.

But the only thing I could do at the moment would be to map the extension to one of the **existing** icons...

**Comment by garretwilson** [comment]
> But the only thing I could do at the moment would be to map the extension to one of the existing icons...

**That would be wonderful for the moment!** It would be much appreciated --- otherwise 90% of my files will appear "unrecognized". Some day one of us can put a little "x" in the corner of the icon, but that's way low on the priority list.

Thanks for the help.

**Comment by icflorescu** [comment]
This should be fixed once the PR is merged.

@Alhadis, @DanBrooker - any chance to push a new release? :-)

**Comment by Alhadis** [comment]
> Some day one of us can put a little "x" in the corner of the icon, but that's way low on the priority list.

Eh, just the HTML5 icon will do. Modifying the icon is overkill, especially when `.erb` and `.phtml` files are more deserving of that treatment.

I wouldn't say this is enough to cut a release over, to be honest. You can view the results now by [using your stylesheets](https://github.com/DanBrooker/file-icons#customisation):

```less
@import "packages/file-icons/styles/items";
@{pane-tab-selector}, .icon-file-text {
	&[data-name$=".xhtml"]:before   { .html5-icon; .medium-orange; }
}
```

**Comment by garretwilson** [comment]
I want to say thank you! I just updated to version 2.0.4, and now all my XHTML5 files aren't ugly anymore --- they all have an HTML icon. Wonderful! I appreciate it.
