### ISSUE TITLE
[Proposal] Logic Programs file icon

### ISSUE THREAD

**Issue by demofrager** [DanBrooker/file-icons#463]
I would like to ask you if you could make a icon for ".lp" files. It's a common file termination for any logical program file like prolog, answer set programing and others, but I don't have any idea of what could be the right icon.

Thank you!
Best Regards

**Comment by demofrager** [comment]
I think the generic code icon would be ok for this case. The assembly one makes no sense as logic programming files usually have a prolog-like syntax; they're hardly assemby. :)

Thank you!
Best Regards

**Comment by Alhadis** [comment]
Alright, I'll make a note to add it to the next release. :) Thanks!

In the mean time, you can just use your stylesheet to customise the filetypes:

```less
@import "packages/file-icons/styles/items";
@{pane-tab-selector}, .icon-file-text {
	&[data-name$=".lp"]:before   { .code-icon; .dark-blue; }
}
```
