### ISSUE TITLE
Support gulpfile.js icon for folder

### ISSUE THREAD

**Issue by haan123** [DanBrooker/file-icons#464]
It would be great if you can support /gulpfile.js folder like https://github.com/vigetlabs/gulp-starter has done in their repo.

**Comment by Alhadis** [comment]
How common is this as a folder name?

**Comment by haan123** [comment]
I'm not sure how common it is, but i'm pretty sure there are many project that split up gulp tasks into multiple files, and you can see in https://github.com/vigetlabs/gulp-starter, there are over 4000 watching for it, so i guess this approach is widely used. :))

**Comment by Alhadis** [comment]
Just add this to your user stylesheet:

```less
@import "packages/file-icons/styles/items";
@{pane-tab-selector}, .icon-file-directory {
	&[data-name="gulpfile.js"]:before {
		.gulp-icon;
		.medium-red;
	}
}
```

This sounds a little too specific to include in the package's core, sorry.

**Comment by haan123** [comment]
i'll do, thanks for your quick support! 👍
