### ISSUE TITLE
Icons not showing when package is manually installed

### ISSUE THREAD

**Issue by smtl** [DanBrooker/file-icons#466]
I wasn't able to download the package through the in built installer in Atom because I was getting an error since I don't have admin rights on the laptop I am using. I downloaded the zip for this package and extracted it to C:\Users\username\.atom\packages.

I restarted atom (I have restarted it a couple of times now) and icons are showing but they are showing incorrectly. JS files have an empty orange/red box instead of the yellow JS logo.

Is there a way I can fix it or is installing it manually just unavailable for this pacakage?

OS: Windows 7

**Comment by smtl** [comment]
It looks like this package cannot be installed by downloading the zip file. Source: https://github.com/DanBrooker/file-icons/issues/425#issuecomment-249350994 

It might be a good idea to stick this info in the install guide.

**Comment by Alhadis** [comment]
Hey @smtl,

Atom packages aren't meant to be installed using zip files. Installation is supposed to be done through the settings view.

If you lack admin rights on the laptop you're using, then it sounds like it could be an installation issue with Atom.
