### ISSUE TITLE
GNU Octave icon for .m files with customFileTypes set accordingly

### ISSUE THREAD

**Issue by fusion809** [DanBrooker/file-icons#470]
Hi,

I have seen the release notes for 2.0 and while it is definitely an important milestone I noticed that my m files are not given the MATLAB logo or any other appropriate logo (the best logo would be GNU Octave's but if this weren't possible I'd accept the use of MATLAB's logo). Despite this in my `~/.atom/config.cson` I have the code snippet:

```cson
   customFileTypes:
      "source.octave": [
        ".m"
      ]
```

So I am here to ask that GNU Octave logo be given to m files when this customFileTypes setting is set. 

Thanks for your time,
Brenton

**Comment by Alhadis** [comment]
Hang on. What's the actual issue here? Not having a more appropriate icon, or *no* icon appearing whatsoever?

If it's the former, you can use your stylesheet to replace the MATLAB icon with something else.

If it's the latter, try `"source.matlab". I noticed `octave` isn't listed in the rule's [`scope`](https://github.com/DanBrooker/file-icons/blob/master/config.cson#L2105) pattern, so that's probably the next thing I'll fix.

**Comment by fusion809** [comment]
Both, I'd prefer the GNU Octave icon to be added, but if it's too challenging to get it (as I don't know if it's in any of the included icon fonts) I'd be willing to settle for octave being added to the scope pattern that gets the MATLAB icon.

**Comment by Alhadis** [comment]
I can manage both, and I've already found the logo as an SVG. ;p

What I need to know is, does the feature work for you or not? Does it show if you add this to your config?

```coffee
customFileTypes:
	"source.matlab": [
		"m"
	]
```

If not, there's a problem. If so, it's only a tiny one.

**Comment by fusion809** [comment]
I'm afraid it doesn't. I even reloaded Atom after changing:

```cson
customFileTypes:
	"source.octave": [
		"m"
	]
```

to:

```cson
customFileTypes:
	"source.matlab": [
		"m"
	]
```

but still I'm seeing this:
![screenshot_20161230_020939](https://cloud.githubusercontent.com/assets/4717341/21547993/1c0f300e-ce35-11e6-90f7-a1a52f3ba11c.png)

**Comment by Alhadis** [comment]
Does removing the leading dot help?

**Comment by fusion809** [comment]
I'll be, it does. Rofl, sorry didn't realize that fairly minor mistake of mine. It works without the dot for matlab but not octave.

**Comment by Alhadis** [comment]
Alright, so there're three improvements to be made:

1. Add support for matching patterns with leading dots
2. Add a separate language entry for Octave, complete with spiffy logo
3. Learn to count to three

**Comment by Alhadis** [comment]
@fusion809 I've fixed the issue with dots, and added `octave` as an alias for MATLAB. The icon itself will have to wait for now, #471 is more important. Sorry, will get back to that.

**Comment by Alhadis** [comment]
Octave icon added in [`v2.0.14`](https://github.com/file-icons/atom/releases/tag/v2.0.14).
