### ISSUE TITLE
Rendering issue on Find File (cmd-p) dialog

### ISSUE THREAD

**Issue by giannisp** [DanBrooker/file-icons#481]
There's a rendering issue while typing on the Find File (cmd-p) dialog.
Seems like drawing a default icon on every keypress.

Atom: 1.12.7
file-icons: 2.0.4

![screencast](https://cloud.githubusercontent.com/assets/1112194/21587539/5054ccbc-d0e6-11e6-840c-7954797fcb47.gif)

**Comment by bdthinh** [comment]
I have exactly same issue. It's really annoying.
Atom: 1.12.7
file-cions: 2.0.4
