### ISSUE TITLE
File icon for Ruby spec gone?

### ISSUE THREAD

**Issue by douglascamata** [DanBrooker/file-icons#483]
I just updated my package and the green ruby icon for my specs are gone. Is this expected or a bug? I loved how helpful that icon is/was.

Thanks for the nice package though, it's the first thing I install in my Atom!

**Comment by Alhadis** [comment]
Can you attach a screenshot? I'm not sure what you mean by specs.

**Comment by douglascamata** [comment]
Oh, sorry. By "specs" I mean a ruby file where we define expectations (just another name for tests). The "specs" are defined with a filename pattern, `*_spec.rb`. Unfortunately, I don't have a screenshot of the old icon, but the current one is: 

![screen shot 2016-12-30 at 13 52 10 2](https://cloud.githubusercontent.com/assets/159076/21603247/f43a9af4-d19b-11e6-93f2-355df5411246.png)

Before this file would show with a similar icon, but in the green color. It was amazing to quickly identify tests and implementation.

**Comment by Alhadis** [comment]
Ah, easily fixed. :-)

**Comment by douglascamata** [comment]
Thanks 👍
