### ISSUE TITLE
Files are being erroneously assigned folder icons in tree view

### ISSUE THREAD

**Issue by fusion809** [DanBrooker/file-icons#484]
Hi,

I've noticed the most bizarre bug, for some reason some of my files are being given the folder icon in tree view. Here is a screenshot showing it, you can see it under the "codelite" folder. (`10.0.tar.gz`, `._service` and `codelite.spec` are all files not folders). Oddly enough when I open up codelite.spec in Atom no tab is shown for it. 

![screenshot_20170103_034850](https://cloud.githubusercontent.com/assets/4717341/21593903/1993c1c4-d168-11e6-8757-4fc3ceb9c3a5.png)

Thanks for your time,
Brenton

**Comment by Alhadis** [comment]
I'm starting to suspect platform-related differences are at play, here. Was an error displayed in the dev tools when you opened the "folder-file"? The one which isn't displaying a tab?

Can you show me the output of `stat -x` for each of those files, please?

**Comment by fusion809** [comment]
It also appears to be intermittent, I re-opened Atom to this very directory and the bug is gone... 
![screenshot_20170103_194444](https://cloud.githubusercontent.com/assets/4717341/21604135/306273c0-d1ed-11e6-8321-cca415aab12a.png)

**Comment by Alhadis** [comment]
So, is this solved, or...?

**Comment by fusion809** [comment]
Wouldn't say it was *solved* unless we knew the cause of it and had implemented a fix. But let's say it's on-hold, I'll close this issue until I get this error again and then I'll collect the data you want.

**Comment by Alhadis** [comment]
@fusion809 Could you run the package specs and tell me if they all pass? You may need to run `apm install .` in the package directory if the `devDependencies` haven't been installed.

**Comment by fusion809** [comment]
How do I run the package specs?

**Comment by Alhadis** [comment]
Open the package in Atom, then run (from the menu bar) **View → Developer… → Run Package Specs**

**Comment by fusion809** [comment]
I ran 'em with the error:

![screenshot_20170115_090050](https://cloud.githubusercontent.com/assets/4717341/21958768/5c16d3f4-db01-11e6-88b3-ea081d468d9b.png)

**Comment by Alhadis** [comment]
Ah, any chance you could clone from master and run the tests there?

(Sorry, I omitted the test fixtures from the distributed package to lessen package filesize...)

**Comment by fusion809** [comment]
Gave
![screenshot_20170115_091304](https://cloud.githubusercontent.com/assets/4717341/21958835/f1ebab9c-db02-11e6-91dc-d1006d751d7c.png)

**Comment by Alhadis** [comment]
Ugh, crap. Thanks...

(I sense this is gonna come down to another VM installation...)

**Comment by Alhadis** [comment]
Or not. Sorry, could you do a fresh pull and try again? :)

(Sorry if I'm busting your chops)

**Comment by fusion809** [comment]
Done with yet another failure.
![screenshot_20170115_092309](https://cloud.githubusercontent.com/assets/4717341/21958912/4d49c752-db04-11e6-8c4c-0e9668c0114d.png)

**Comment by Alhadis** [comment]
Alright, so that confirms my hunch that Linux systems [might be handling](https://github.com/file-icons/atom/issues/514#issuecomment-272403113) `document.styleSheets` differently to macOS. Thanks mate. :)

Guess this will need VMWare intervention after all. Sigh...
