### ISSUE TITLE
Line number: 29 'packages/file-icons/styles/colors.less' wasn't found

### ISSUE THREAD

**Issue by charlesdg** [DanBrooker/file-icons#487]
I have this error during each atom loading:

```
Error compiling Less stylesheet: /Users/charlesdegroote/.atom/styles.less
Line number: 29
'packages/file-icons/styles/colors.less' wasn't found
```

Any idea?

**Comment by jesusgalvan** [comment]
I have something similar every time I open a window:
![image](https://cloud.githubusercontent.com/assets/2798097/21623183/0fe8cf2c-d1b6-11e6-8f9b-d5d6d3535e17.png)

Any solutions?

**Comment by Alhadis** [comment]
Please see the [Troubleshooting](https://github.com/DanBrooker/file-icons#troubleshooting) section in the README. You need to update your stylesheets:

>As of [v2.0](https://github.com/DanBrooker/file-icons/releases/tag/v2.0.0), classes are used for displaying icons instead of mixins. Delete lines like these from your stylesheet:
>
>~~~diff
>-@import "packages/file-icons/styles/icons";
>-@import "packages/file-icons/styles/items";
>-@{pane-tab-selector},
>.icon-file-directory {
> 	&[data-name=".git"]:before {
>-		.git-icon;
>+		font-family: Devicons;
>+		content: "\E602";
>	}
>}
>~~~
>
>Instead of `@pane-tab…` variables, use `.tab > .icon[data-path]`:
>
>~~~diff
>-@pane-tab-selector,
>-@pane-tab-temp-selector,
>-@pane-tab-override {
>+.tab > .icon {
> 	&[data-path$=".to.file"] {
> 		
> 	}
>}
>~~~
>
>These CSS classes are no longer used, so delete them:
>
>~~~diff
>-.file-icons-force-show-icons,
>-.file-icons-tab-pane-icon,
>-.file-icons-on-changes
>~~~

**Comment by bsr203** [comment]
could you please help me to translate my old settings
```
@import "packages/file-icons/styles/colors"; // to use the colours
@import "packages/file-icons/styles/icons";  // to use the defined icons
@import "packages/file-icons/styles/items";
@{pane-tab-selector}, .icon-file-text {
  &[data-name$="_test.go"]          { .dark-blue;             } // Colours icon and filename
  &[data-name$="_test.go"]:before   { .go-icon; .dark-blue; } // Colours icon only
}
```
thanks.
bsr.

**Comment by Alhadis** [comment]
@bsr203 Like this:

```css
.go-icon[data-name$="_test.go"]:before{
	color: #46788d;
}
```

**Comment by bsr203** [comment]
thank you so much. no error, but unfortunately I am hit with https://github.com/file-icons/atom/issues/471

I use nuclide, and I could see the icons on the tabs, but not on file tree. Hope it get fixed nuclide side.

thanks again for your help.
bsr.

**Comment by MiracleBlue** [comment]
Very thankful for this thread, however, how does one now specify a particular icon to use from the file-icons set?  Are we supposed to manually insert the content string with the code required?  What was the reasoning for eliminating the convenience mixins for this?  It's certainly a lot more difficult to have to look these codes up now as opposed to when we had the very handy mixins, although it's something I can live with I'd love to find out more about that.

Thanks for all your work on this great plugin, looking forward to seeing this one get better and better :)

**Comment by Alhadis** [comment]
Hi Nick, remember me? Ol' mate John. I'm the bloke responsible for this mess. Didn't know you used Atom. ;p

To give you the TL:DR of it: the previous implementation barred use of class additions to DOM elements, which was pivotal to implementing dynamic icon assignment (e.g., hashbangs, modelines, et cetera). Yes, it's a little more work for a user to insert a content string, but it permits full flexibility, and eliminates the rotten precompilation step that plagued users with every upgrade.

But hey, that's why I purposefully went out of the way to map each icon font's character-set [as explicitly as possible](https://github.com/file-icons/atom#icon-reference).

**Comment by Alhadis** [comment]
Also, bruh, I thought you died. My e-mails to you bounced and you fell off the face of the Earth. Or I did. We both did. Hell, I don't fuckin' remember, hahahah.

**Comment by MiracleBlue** [comment]
Bruh!!  Where did you go??  I thought **you** disappeared from the face of the earth!  Ha!  Srsly man I've been wondering where you went for ages.  Good to see you on here!  Yes, I'm an obsessive atom user :P Also yeh my old old old email address is long dead... I'll email you my new deets to your email address on your github profile!  I'm also in Melbourne now with the family, so perhaps we'll catch up sometime!

**Comment by Alhadis** [comment]
I'M DEPRESSED AND JOBLESS, HELP ME GIT OUTTA HERE.

Some people drink to deal with depression and unemployment. Me, I just code harder and harder until sleep becomes a forgotten memory.

I'm not kidding, either. All of these were done as *breaks* while working on File-Icons V2:
- [Atom-Mocha](https://github.com/Alhadis/Atom-Mocha)
- [Print](https://github.com/Alhadis/Print)
- [Chai-Untab](https://github.com/Alhadis/Chai-Untab)

And the following language grammars, which are now supplying syntax highlighting across GitHub:
- [FontForge grammar](https://github.com/Alhadis/language-fontforge)
- [Roff / Unix manual pages](https://github.com/Alhadis/language-roff)
- [Emacs Lisp](https://github.com/Alhadis/language-emacs-lisp)
- [Apollo 11's](https://github.com/chrislgarry/Apollo-11) [fucking source code](https://github.com/Alhadis/language-agc)
- [Turing](https://github.com/Alhadis/language-turing)
- [APL](https://github.com/Alhadis/language-apl)
- [Wavefront OBJ/Material files](https://github.com/Alhadis/language-wavefront)
- [Vim Script](https://github.com/Alhadis/language-viml) (Originally transferred to me, but I cleaned it up so much it pretty much became a full rewrite)
- And oh yeah, cleaning up almost 300 icons by hand in Illustrator for this package ([Mfixx](https://github.com/Alhadis/MFixx) + [DevOpIcons](https://github.com/Alhadis/DevOpicons))

Which isn't even touching on the shitloads of pull requests, [some of which have taken months to review](https://github.com/Alhadis/language-css).

... alright, I'll stick to e-mail from now on... give our watchers a rest, hahaha

**Comment by MiracleBlue** [comment]
Jesus, you're a machine.  Also yeh send me your deets man, already sent an email to you with mine :) I'm ~stalking~ perusing your repos, this is awesome.
