### ISSUE TITLE
Missing Docker icon on `docker-compose` files

### ISSUE THREAD

**Issue by esBeee** [DanBrooker/file-icons#489]
Since the update yesterday the icons for files like `docker-compose.yml` or `docker-compose.development.yml` are the standard `.yml` icons, instead of the Docker (whale) icons. Is this by design or a bug? Definitely feels like something is missing (probably it's the whale) 🙂.

**Comment by SnO2WMaN** [comment]
https://github.com/file-icons/atom/commit/69c756827433a6ef68299eca6eb0581165adb610#r37720637
