### ISSUE TITLE
React jsx icon

### ISSUE THREAD

**Issue by bittersweetryan** [DanBrooker/file-icons#91]
Now that React.js is taking over the JS world it's time to get a dedicated icon for it!

**Comment by jonywtf** [comment]
Please, add coffeescript react icon for *.cjsx files too!)

![cjsx](https://cloud.githubusercontent.com/assets/7776600/6163084/cd238bda-b2a6-11e4-87d8-a443c1dd68eb.png)

**Comment by DanBrooker** [comment]
@jonywtf done -> d689323ab5fbb27b6395a03a4f995baed2881840

@bittersweetryan We'll just have to wait until someone adds it to an icon font

**Comment by DanBrooker** [comment]
Just merged #124 which has a jsx icon by @roman01la
