### ISSUE TITLE
Sublime Tabs support

### ISSUE THREAD

**Issue by enilsen16** [DanBrooker/file-icons#92]
I know its already mentioned in the README but it would be great if the file icons also worked with the package [sublime tabs](https://github.com/ddavison/sublime-tabs). 

With Sublime Tabs enabled, I see the icons in the tree view but not in the tabs:

![atom](http://i.imgur.com/yxhqGIXl.png)

Maybe @ddavison can comment if this is a possibility, Thanks!

**Comment by njoannidi** [comment]
Created pull request on sublime-tabs to fix this issue:
https://github.com/ddavison/sublime-tabs/pull/87

**Comment by ddavison** [comment]
Merged in!   Published as v.0.5.3.  Now, I don't use file-icons, so hopefully that does fix it

**Comment by roman01la** [comment]
Nice! Can we maybe pull icons a couple of pixels up?
![screen shot 2015-04-11 at 4 43 36 pm](https://cloud.githubusercontent.com/assets/1355501/7101615/35ee7fb2-e06a-11e4-8004-d0286b423b82.png)

**Comment by roman01la** [comment]
Also, when in a view mode, the icon gets italic style. Doesn't look good, imo
![screen shot 2015-04-11 at 8 50 57 pm](https://cloud.githubusercontent.com/assets/1355501/7102570/a12aaff4-e08c-11e4-83dc-0b4a4281276b.png)

**Comment by DanBrooker** [comment]
The icons are set to `vertical-align: middle;`
![screen shot 2015-04-12 at 8 56 33 am](https://cloud.githubusercontent.com/assets/714197/7103237/e1137424-e0f1-11e4-95b9-b453b9a18c53.png)
Although your icons do look lower than expected, maybe your theme?

**Comment by roman01la** [comment]
Oh, hell, yes... didn't think about theme styles. And I did a PR into file-icons to fix this, shit :D
Is there a way to abstract from theme styles?

**Comment by DanBrooker** [comment]
Haven't seen a way to add css per theme, except in the theme. There's always the user stylesheet.
Or possibly a setting to switch to baseline alignment

**Comment by roman01la** [comment]
Hmm, I'm using standard One Dark theme, also tried to switch to the one you are using (Atom Dark I guess), still same: positioned lower and italicized when in tmp mode. Also `vertical-align: middle;` is applied on icons.

**Comment by roman01la** [comment]
Also tried to turn off all plugins, still same.

**Comment by DanBrooker** [comment]
Sublime tabs has been deprecated
